### ISSUE TITLE
[i3 module]using label-focused-background causes whole bar to change color

### ISSUE THREAD

**Issue by ridelore** [jaagr/lemonbuddy#100]
I am not sure if that's a bug or a misconfiguration. I am using colors in the i3 module to hilight the active desktop but every time I change to the last active Desktop the whole bar changes its color.

Screenshots: 

That's how it's supposed to look Desktop 2 is active an hilighted in blue: http://imgur.com/qsgW02v.png
That happens when I change to Desktop 5 the bar right to the i3 module is now also blue: http://i.imgur.com/w2ixeOn.png

relevant snippets from my configuration:
bar config: http://pastie.org/10943977
i3 module config: http://pastie.org/10943978

**Comment by jaagr** [comment]
That's weird, I'll have a look at it.

**Comment by jaagr** [comment]
Should be fixed with the latest commit. Please verify.

**Comment by ridelore** [comment]
Yup, all fine now. Thanks a bunch!
