### ISSUE TITLE
Network module reports unknown essid

### ISSUE THREAD

**Issue by p4block** [jaagr/lemonbuddy#101]
Running Arch Linux, using NetworkManager to connect to networks, wireless_tools is installed

The network module detects my IP address and bandwidth usage correctly, however reports the essid parameter as UNKNOWN

No errors are outputted by the program in the cli and `iwgetid` successfully reports it.

What could be happening?

**Comment by jaagr** [comment]
I will have a look.

**Comment by jaagr** [comment]
Hi could you see if this is still valid after updating to the latest version.

DId some cleanup of the network module in 82f311b6950f07b9409fd5ef812609d2f49c80d0.

**Comment by jaagr** [comment]
Closing this, reopen if the patch didn't fix the issue.

**Comment by p4block** [comment]
Sorry for the late response. Got the update.

Now the bar crashes with core dumped if the network module is enabled. Could be unrelated.

How do I provide proper logging on it?

**Comment by jaagr** [comment]
Follow these steps:

- Install `gdb`
- Execute `gdb --args lemonbuddy yourbar`
- Type `run`
- When the crash occurs type `bt`
- Copy the output

Make sure you update to the latest version.

**Comment by p4block** [comment]
The last update to lemonbuddy in the AUR fixed the problem for me, thank you for the hard work.

**Comment by jaagr** [comment]
Great! Please report any other issues you bump in to... or if you have any suggestions on improvement etc.
