### ISSUE TITLE
Bar instantly closes after it's started.

### ISSUE THREAD

**Issue by Capuno** [jaagr/lemonbuddy#102]
I have set it to start the bar with the same script as in the tutorial, but whenever I start or restart i3 the bar appears like half a second and then dissapears, the same happens when I try to run it without root access on the terminal, it says `Segmentation fault (core dumped)`, it works with sudo lemonbuddy or running the script as root, but I thought i3 config ran as root and it's not working.

**Comment by jaagr** [comment]
I would need more details to be able to help you. Your configuration, how you launch it etc. Are you saying that just executing `lemonbuddy yourbar` in your terminal is causing a segfault?

**Comment by jaagr** [comment]
I just pushed a fix for a bug (see #104) causing a segfault. This could very well be the reason you can't launch your bar. Could you upgrade to the latest version and try again?

**Comment by Capuno** [comment]
Now its working perfectly, thanks, and awesome work :D
