### ISSUE TITLE
Error building -- Missing dependancy?

### ISSUE THREAD

**Issue by zacknorman** [jaagr/lemonbuddy#103]
Followed your dependency instructions, upon issuing the command 'sudo cmake -DCMAKE_BUILD_TYPE=Release ..' I recieve

-- Boost version: 1.61.0
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find X11_XCB (missing: X11_XCB_LIBRARIES X11_XCB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindX11_XCB.cmake:28 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:92 (find_package)

**Comment by zacknorman** [comment]
Alright, just fixed it with installing the libx11-xcb-dev package -- might wanna add that to your dependancy section for the install instructions! Cheers!

**Comment by jaagr** [comment]
Thanks for reporting it.. What distro are you using?

**Comment by zacknorman** [comment]
Ubuntu 16.04 LTS with i3 >> One more thing, upon issuing the cmake command i'm getting  new error

CMake Error at CMakeLists.txt:113 (add_subdirectory):
  The source directory

    /home/oz0ne/lemonbuddy/lib/xpp

  does not contain a CMakeLists.txt file.


any help is appreciated mate

**Comment by jaagr** [comment]
Did you initialize the submodules when cloning the repo?

**Comment by zacknorman** [comment]
turns out i didnt follow your instructions correctly... My apologies 

thanks

**Comment by jaagr** [comment]
Great. Please report any other issues you might find, especially while using i3 since I'm not using it myself (other than quick test runs)
