### ISSUE TITLE
Battery 'file not found'

### ISSUE THREAD

**Issue by kyentei** [jaagr/lemonbuddy#108]
When trying to add the battery module I get the following error:
```bash
error: module/battery: battery_module: The file '/sys/class/power_supply/ADP1/online' does not exist
warning: Stopping 'module/battery'...
```

Is there any way to specify the path to the battery? Mine isn't at ADP1/online. Using a custom script is way less pretty.

**Comment by jaagr** [comment]
Yeah check the wiki, there's an option to set the battery and adapter name.

**Comment by kyentei** [comment]
Entirely looked past that. My apologies. Thanks for your quick reply

**Comment by jaagr** [comment]
No worries :-)
