### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by LordNDHuy** [jaagr/lemonbuddy#111]
` Checking for module 'jsoncpp>=1.7.0'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  lib/i3ipcpp/CMakeLists.txt:13 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/huynguyen/lemonbuddy/build/CMakeFiles/CMakeOutput.log".
See also "/home/huynguyen/lemonbuddy/build/CMakeFiles/CMakeError.log".
 err  Failed to generate build... read output to get a hint of what went wrong
`
sorry i have installed all needed
but it still turns out like that
can you help me plz?

**Comment by jaagr** [comment]
I will fix the dependency issue

**Comment by jaagr** [comment]
jsoncpp is built statically now so this should no longer be a problem
