### ISSUE TITLE
Strange CPU bars behaviour

### ISSUE THREAD

**Issue by platipo** [jaagr/lemonbuddy#113]
I'm a noob but i heve seen that after the v2 update CPU bars behave strangely
![rsz_2016-10-21-144915_1024x600_scrot](https://cloud.githubusercontent.com/assets/22260641/19602905/4da56a50-97af-11e6-864b-ca147090d9d8.png)
![rsz_2016-10-21-144911_1024x600_scrot](https://cloud.githubusercontent.com/assets/22260641/19603117/3bb4c218-97b0-11e6-9f80-c754cea71fd2.png)

**Comment by jaagr** [comment]
What's the issue?

**Comment by z1lt0id** [comment]
When lemonbuddy is loaded up it uses quite a large amount of CPU.  This is with the process running.
![7biqf_tmp w4691ohypr](https://cloud.githubusercontent.com/assets/2316366/19630840/1d0dfb92-99de-11e6-9f43-9f152e0fee02.png)

And without.
![wsaow_tmp vvzzokxloy](https://cloud.githubusercontent.com/assets/2316366/19630846/27e4a138-99de-11e6-965b-eaa35e695014.png)

Only happened very recently, tried on multiple systems and the same issue appears.

**Comment by platipo** [comment]
I wasn't referring to the performance issues but on the rendering one; CPU bars config here: 
```
[module/cpu]
type = internal/cpu
interval = 0.5
format = <label> <ramp-coreload>
label = CPU

ramp-coreload-0 = ▁
ramp-coreload-0-font = 3
ramp-coreload-0-foreground = #aaff77
ramp-coreload-1 = ▂
ramp-coreload-1-font = 3
ramp-coreload-1-foreground = #aaff77
ramp-coreload-2 = ▃
ramp-coreload-2-font = 3
ramp-coreload-2-foreground = #aaff77
ramp-coreload-3 = ▄
ramp-coreload-3-font = 3
ramp-coreload-3-foreground = #aaff77
ramp-coreload-4 = ▅
ramp-coreload-4-font = 3
ramp-coreload-4-foreground = #fba922
ramp-coreload-5 = ▆
ramp-coreload-5-font = 3
ramp-coreload-5-foreground = #2aaff77
ramp-coreload-6 = ▇
ramp-coreload-6-font = 3
ramp-coreload-6-foreground = #ff555
ramp-coreload-7 = █
ramp-coreload-7-font = 3
ramp-coreload-7-foreground = #ff555
```
https://github.com/platipo/dotfiles/blob/master/config/lemonbuddy/config

In fact often the bars don't render the right colors: the appears randomly white/black. I don't know if I'm mistaking something

**Comment by jaagr** [comment]
@z1lt0id could you show me your configuration because with my config it is using between 0.0-1.3%.. and what compiler did you build the project with? i've noticed some undefined behavior when built with gcc and optimizations turned on..

**Comment by jaagr** [comment]
@platipo it looks like the colors are incorrect in your setup.. `#ff555` is not a valid rgba value

**Comment by jaagr** [comment]
@platipo this is the module config I use myself.. 

~~~dosini
[module/cpu]
type = internal/cpu
interval = 0.5

format = <label> <ramp-coreload>

label = CPU
label-font = 3
label-foreground = #99

ramp-coreload-0 = ▁
ramp-coreload-0-font = 2
ramp-coreload-0-foreground = #aaff77
ramp-coreload-1 = ▂
ramp-coreload-1-font = 2
ramp-coreload-1-foreground = #aaff77
ramp-coreload-2 = ▃
ramp-coreload-2-font = 2
ramp-coreload-2-foreground = #aaff77
ramp-coreload-3 = ▄
ramp-coreload-3-font = 2
ramp-coreload-3-foreground = #aaff77
ramp-coreload-4 = ▅
ramp-coreload-4-font = 2
ramp-coreload-4-foreground = #fba922
ramp-coreload-5 = ▆
ramp-coreload-5-font = 2
ramp-coreload-5-foreground = #fba922
ramp-coreload-6 = ▇
ramp-coreload-6-font = 2
ramp-coreload-6-foreground = #ff5555
ramp-coreload-7 = █
ramp-coreload-7-font = 2
ramp-coreload-7-foreground = #ff5555
~~~

**Comment by jaagr** [comment]
And the font I'm using for the bar's is `font-1 = Unifont:size=5;-3`

**Comment by z1lt0id** [comment]
Here is the config :)  I just compiled it with aur but I'll check to see if that uses clang or not.

https://bin.fsociety.info/ducunuxote

**Comment by z1lt0id** [comment]
Never mind it was my scripts that were doing it

**Comment by jaagr** [comment]
@z1lt0id ok cool, so you got it fixed?

**Comment by platipo** [comment]
Thanks for your support @jaagr
