### ISSUE TITLE
Error when building/sudo make installing. 

### ISSUE THREAD

**Issue by Kobblander** [jaagr/lemonbuddy#115]
[cmakeOutput.txt](https://github.com/jaagr/lemonbuddy/files/546059/cmakeOutput.txt)
I have gcc 5.4.1 and have installed all the dependencies I think. Note: I had to manually install jsoncpp to be able to build with cmake

After building with cmake -DCMAKE_BUILD_TYPE=Release, sudo make install fails with the following output:

Scanning dependencies of target xpp
Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  0%] Built target xpp
Scanning dependencies of target i3ipc++
[ 25%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
[ 50%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
Linking CXX static library libi3ipc++.a
[ 50%] Built target i3ipc++
Scanning dependencies of target lemonlib_static
[ 75%] Building CXX object bin/CMakeFiles/lemonlib_static.dir/lemonbuddy.cpp.o
Linking CXX static library liblemonlib.a
[ 75%] Built target lemonlib_static
Scanning dependencies of target lemonbuddy
[100%] Building CXX object bin/CMakeFiles/lemonbuddy.dir/main.cpp.o
In file included from /home/jakobat/Documents/lemonbuddy/lemonbuddy/include/components/logger.hpp:7:0,
                 from /home/jakobat/Documents/lemonbuddy/lemonbuddy/include/components/config.hpp:8,
                 from /home/jakobat/Documents/lemonbuddy/lemonbuddy/src/main.cpp:6:
/home/jakobat/Documents/lemonbuddy/lemonbuddy/include/utils/string.hpp: In function ‘auto lemonbuddy::v2_0_0::string_util::replace_all(const string&, std::string, std::string)’:
/home/jakobat/Documents/lemonbuddy/lemonbuddy/include/utils/string.hpp:59:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (int i = 0; i < haystack.length(); i++) {
                       ^
cc1plus: all warnings being treated as errors
make[2]: *** [bin/CMakeFiles/lemonbuddy.dir/main.cpp.o] Error 1
make[1]: *** [bin/CMakeFiles/lemonbuddy.dir/all] Error 2
make: *** [all] Error 2

**Comment by Kobblander** [comment]
I finally managed to install lemonbuddy!!
What I did was to install clang version 3.8 and using the following command:
$cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-3.8 ..
and then
$sudo make install

This fixed all my problems :)

**Comment by jaagr** [comment]
Thanks for reporting the issues.. the build needs som debugging if built with gcc... I always build with clang myself
