### ISSUE TITLE
Error with volume module

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/lemonbuddy#116]
While connected to HDMI and with "pulseaudio-alsa" installed, the volume module is working but  is not updating when i scroll it up and down. On the other hand if i remove "pulseaudio-alsa" the volume update but do not work.

> [module/Volume]
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 9
label-muted = Muted
format-volume = <ramp-volume> <label-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 

**Comment by jaagr** [comment]
The scroll-up/scroll-down issue is a known bug.. I'm working on a fix
