### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by edricgarran** [jaagr/lemonbuddy#117]
The bar is segfaulting right after startup.
Installed from AUR package lemonbuddy-git
Output from running it with GDB:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff38e2700 (LWP 16540)]
[New Thread 0x7ffff30e1700 (LWP 16541)]
[New Thread 0x7ffff28e0700 (LWP 16543)]
[New Thread 0x7ffff20df700 (LWP 16544)]
[New Thread 0x7ffff18de700 (LWP 16545)]
[New Thread 0x7ffff10dd700 (LWP 16546)]

Thread 7 "lemonbuddy" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff10dd700 (LWP 16546)]
0x0000000000478d3f in lemonbuddy::v2_0_0::drawtypes::ramp::get_by_percentage(float) ()

> edit jaagr: bug fixed in d2187f4

**Comment by jaagr** [comment]
Thanks for reporting the issue, and especially for supplying the gdb output.. makes it easy to fix

**Comment by japhir** [comment]
I also get segfaults when running the AUR-git package. 
It only happens when I launch a second bar. I get some varying warning messages:

    warning: Lost systray selection, deactivating...
    error: module/i3: Socket connection closed...
    warning: Stopping 'module/i3'...
    warning: Termination signal received, shutting down...

and when I retry:

    warning: Lost systray selection, deactivating...
    [2]  - 2036 segmentation fault (core dumped)  lemonbuddy external

dmesg gives me

    [ 5704.012939] lemonbuddy[2044]: segfault at 0 ip 00000000004a3a44 sp 00007f9f0cf27870 error 4 in lemonbuddy[400000+1a9000]

could be a [config error](https://github.com/japhir/ArchConfigs/blob/master/Laptop/lemonbuddyconfig), only just started using lemonbuddy.

**Comment by jaagr** [comment]
Thanks for reporting. Found the bug... I'll push a fix

**Comment by japhir** [comment]
Awesome, thanks!

**Comment by jaagr** [comment]
Should be fixed with 91a9bb6 please verify

**Comment by japhir** [comment]
For me removing the second `tray-position = ...` already fixed the issue. Thanks for the update.

**Comment by jaagr** [comment]
Ok cool.. closing
