### ISSUE TITLE
Network module shows "Not connected"

### ISSUE THREAD

**Issue by beanaroo** [jaagr/lemonbuddy#118]
```dosini
[module/wired-network]
type = internal/network
interface = enp2s0

interval = 3.0

label-connected = %{T3}%local_ip%%{T-}
label-disconnected = %{T3}Not connected%{T-}
label-disconnected-foreground = #66
```
Built-in support for internal/network. Interface is correct. 
```
$ lemonbuddy example -l info
* Starting application...
* Activating traymanager
```

**Comment by jaagr** [comment]
Thanks for reporting the issue. I haven't made any testing for wired network interfaces since the 2.0 update. I will look into it.

**Comment by jaagr** [comment]
Could you verify the fix

**Comment by BenoitAverty** [comment]
It fixed it for me. Thanks !

**Comment by Doshirae** [comment]
The error seems to be here again
It says that my (wireless) interface is disconnected, whereas it actually is 
(and, of course, the interface is correct)

**Comment by patrick96** [comment]
@Doshirae please open a new issue. The original issue occured more than one major update ago and when this project still was called lemonbuddy, so they are probably unrelated.
