### ISSUE TITLE
Transparency is not working properly

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/lemonbuddy#119]
Some modules are not working right when i use rgba colors. Here is an example with Volume module:
http://imgur.com/a/OLtdN
Custom scripts like the window title (using exec = xtitle -s) or the date/clock module, are not working too.

**Comment by jaagr** [comment]
Thanks for reporting the issue. Could you post the config you are using and I'll look into it.

**Comment by jonathashenriques** [comment]
Sure. Here it is:

> ;====================================================;
;						     ;
;   To learn more about how to configure Lemonbuddy  ;
;   go to https://github.com/jaagr/lemonbuddy	     ;
;						     ;
;   The README contains alot of information	     ;
;						     ;
;====================================================;

[settings]

[bar/Bar]
bottom = false
dock = false
width = 100%
height = 24
lineheight = 3
border-top = 8
border-bottom = 1
border-left = 8
border-right = 8
padding-left = 2
padding-right = 1
module-margin-right = 2
modules-left = i3 Spotify
modules-center = Xtitle
modules-right = Volume Clock Shutdown
tray-position = right
background = #f2f2f2
font-0 = tewi:size=9;1
font-1 = -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1

[module/i3]
type = internal/i3
label-focused = 
label-focused-padding = 1
label-unfocused = 
label-unfocused-padding = 1
label-urgent = 
label-urgent-padding = 1
label-visible = 
label-visible-padding = 1
format-foreground = #0d000000

[module/Spotify]
type = custom/script
exec = ~/.config/lemonbuddy/Scripts/Spotify/Spotify.sh
interval = 5
maxlen = 40
ellipsis = true
scroll-up = xdotool key super+0
scroll-down = xdotool key super+z
format-padding = 1
format-foreground = ${bar/Bar.background}
format-background = #0d000000
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Xtitle]
type = custom/script
exec = xtitle -s
tail = true
maxlen = 40
ellipsis = true
format-foreground = #0d000000

[module/Volume]
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 9
label-muted =  Muted
format-volume = <ramp-volume>
format-muted = <label-muted>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = #0d000000
format-muted-foreground = #0d000000
label-muted-foreground = #0d000000

[module/Clock]
type = internal/date
date = %a, %d %b | %H:%M
interval = 5
format-padding = 2
format-foreground = ${bar/Bar.background}
format-background = #0d000000
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Shutdown]
type = custom/script
exec = echo " "
click-left = shutdown now
click-right = reboot
click-middle = xdotool key super+shift+e
format-padding = 1
format-foreground = #0d000000

**Comment by jonathashenriques** [comment]
Another issue is, if RGBA color is set to #00000000, there is no transparency and everything becomes black. But ,if i set color to #00ffffff, which is the same thing (0% opacity on both), everything just works fine.

**Comment by jaagr** [comment]
Yeah that sounds like a bug. Will have a look once I'm done with the new update.

**Comment by jaagr** [comment]
`#00000000` becomes fully transparent for me. Your configuration also shows transparency so this doesn't seem to be a problem with lemonbuddy. What compositor are you using?

**Comment by jonathashenriques** [comment]
Using xcompmgr and compton, both are not working.

**Comment by jonathashenriques** [comment]
You got transparency even on the xtitle and volume module ?

**Comment by jaagr** [comment]
Yeah... with `format-background = #0d000000`

![trans](https://cloud.githubusercontent.com/assets/3697186/19706338/aa917956-9b11-11e6-9e19-364a12cbe442.png)

**Comment by jonathashenriques** [comment]
Sorry, but i mean a transparent foreground, like the icon on the volume module that i posted.

**Comment by jaagr** [comment]
![trans](https://cloud.githubusercontent.com/assets/3697186/19706526/88d5a7b4-9b12-11e6-93ae-e38d967b631d.png)

**Comment by jonathashenriques** [comment]
Ok, i give up. Thank you for the help and attention.

**Comment by jaagr** [comment]
![trans](https://cloud.githubusercontent.com/assets/3697186/19706678/777533e4-9b13-11e6-90a2-d7579f9ee8da.png)

**Comment by jaagr** [comment]
Make sure you are using an up-to-date version and that your compositor is running properly and it should work. Good luck.

**Comment by jonathashenriques** [comment]
shoulThe mistake was mine, i do not made myself clear. I know that the icon foreground from volume module works fine with the rgba colors, and that is awesome BTW. But, here the output of xtitle and the <label-volume>, or the Spotify output texts, all do not work with that. In my print maybe you can see it, a transparent icon and a black "61%" that should be transparent too. Anyway, sorry about the issue report and my bad english.

**Comment by jaagr** [comment]
I changed to a white background and now I see what you mean.. Actually the transparency is working fine it's just that the layers don't blend (the icon is clipping through the bar).

**Comment by jaagr** [comment]
This only happens when using an X font. Freetype fonts blend correctly.

**Comment by jaagr** [comment]
Now the color should be displayed correctly for X fonts as well...

**Comment by jonathashenriques** [comment]
Okay, i recompiled it and now rgba bitmap and x fonts are black :/

**Comment by jaagr** [comment]
What rgba value are you using?

**Comment by jonathashenriques** [comment]
foreground = #99ffffff

**Comment by jaagr** [comment]
And it draws the text in black?

**Comment by jonathashenriques** [comment]
Yes. Also, changing the wallpaper does not affect the font, maybe i'm missing something.

**Comment by jaagr** [comment]
The wallpaper affect the content when using an alpha transparent background for the bar.

**Comment by jaagr** [comment]
Tried on a few different setups now and all render the text in gray so check ur config.

**Comment by jonathashenriques** [comment]
I know, and i'm using it right now. Good, the text is grey now. Did your setups changed the font color while changing wallpapers ? Print: http://imgur.com/a/FPsLw

**Comment by jonathashenriques** [comment]
Looks like the rgba is changing the opacity of the color but not making it transparent.

**Comment by jaagr** [comment]
This should do the trick. Update and reload.

**Comment by jaagr** [comment]
Should probably make that a config setting though.. to not screw up setups without compositorsw

**Comment by jonathashenriques** [comment]
Sorry, the bug persists.

**Comment by jaagr** [comment]
Pushing a fix in a bit...

**Comment by jonathashenriques** [comment]
Alright :)

**Comment by jaagr** [comment]
Xft is just horrible. I revert my "in a bit" comment but I'm working on it.

**Comment by jonathashenriques** [comment]
It's all fine. I don't know how to use non X fonts on lemonbuddy. At the moment i'm using tewi.

**Comment by jonathashenriques** [comment]
Looks like the transparent text is now fully disabled. Any update ?

**Comment by jaagr** [comment]
Not yet. Did you change your config? If so, could you link it so I can test it out. My config works fine however the alpha value probably only brings it more to black and I'm using a dark background.

**Comment by jonathashenriques** [comment]
Actually not much. Look's like this: 


[settings]

[bar/Bar]
bottom = false
dock = false
width = 100%
height = 24
lineheight = 3
border-top = 8
border-bottom = 1
border-left = 8
border-right = 8
padding-left = 2
padding-right = 1
module-margin-right = 2
modules-left = i3 Spotify
modules-center = Xtitle
modules-right = Volume Clock Shutdown
tray-position = right
background = #99f2f2f2
font-0 = tewi:size=9
font-1 = -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1;0

[module/i3]
type = internal/i3
label-focused = 
label-focused-padding = 1
label-unfocused = 
label-unfocused-padding = 1
label-urgent = 
label-urgent-padding = 1
label-visible = 
label-visible-padding = 1
format-foreground = #0d000000

[module/Spotify]
type = custom/script
exec = ~/.config/lemonbuddy/Scripts/Spotify/Spotify.sh
interval = 5
maxlen = 40
ellipsis = true
scroll-up = xdotool key super+0
scroll-down = xdotool key super+z
format-padding = 1
format-foreground = ${bar/Bar.background}
format-background = #0d000000
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Xtitle]
type = custom/script
exec = xtitle -s
tail = true
maxlen = 40
ellipsis = true
format-foreground = #0d000000

[module/Volume]
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 9
label-muted = 
format-volume = <ramp-volume> <label-volume>
format-muted = <label-muted>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = #0d000000
format-muted-foreground = #0d000000
label-muted-foreground = #0d000000

[module/Clock]
type = internal/date
date = %a, %d %b | %H:%M
interval = 5
format-padding = 2
format-foreground = ${bar/Bar.background}
format-background = #0d000000
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Shutdown]
type = custom/script
exec = echo " "
click-left = shutdown now
click-right = reboot
click-middle = xdotool key super+shift+e
format-padding = 1
format-foreground = #0d000000

**Comment by jonathashenriques** [comment]
You said that the freetype fonts are working just fine. Can you tell me how i can use some of these freetype fonts, please ?

**Comment by jaagr** [comment]
- Get a list of fonts using `fc-list | cut -d ' ' -f2 | sort -u`
- Specify size using `:size=12`

Example: `font-0 = terminus:style=bold:size=12`

**Comment by jonathashenriques** [comment]
Thanks ! Sadly they are not working. I will wait until a new update.

**Comment by jaagr** [comment]
ah.. it's my dev build. I'm progressing at least so I'll keep you posted.

**Comment by jaagr** [comment]
Great success... 
![trans](https://cloud.githubusercontent.com/assets/3697186/19833355/15ef0fbc-9e3f-11e6-9d39-d43f7ca70e3b.png)

**Comment by jaagr** [comment]
transparency now works properly for freetype fonts... If you are using a git version you can grab the latest version.. X fonts aren't fix yet.

**Comment by jonathashenriques** [comment]
THIS IS AWESOMEEEE ! Can you tell me what font are you using, please ?

**Comment by jaagr** [comment]
In the blue pic?

**Comment by jonathashenriques** [comment]
Can you please tell me if it's working with your clock module ?

**Comment by jonathashenriques** [comment]
Sadly, mine still changing only opacity, but not getting transparent (look at the window title, for example). The good news are: the icons of seji-font are now working again with the rgba colors.
![2016-10-30-030947_1920x1080_scrot](https://cloud.githubusercontent.com/assets/21113681/19834633/5ad63696-9e4e-11e6-98a4-e310111b8f68.png)

**Comment by jonathashenriques** [comment]
I'm so sorry about all the work that you have just to fix this :/

**Comment by jaagr** [comment]
Yeah, now it does (d8c309ec3571254402d5e5210a99e28f407196d8)... was a bug in the date module.

**Comment by jaagr** [comment]
Can't see what's wrong in that image. The green color?

**Comment by jonathashenriques** [comment]
Yeah, it should be blue, cause is set to #9900ff00. Am i doing something wrong ?

**Comment by jonathashenriques** [comment]
Everything else is working flawless. i3 Module, for example, is perfect, fully transparent, matching the wallpaper color.

**Comment by jaagr** [comment]
The third bit is blue. `#990000ff`

**Comment by jonathashenriques** [comment]
I hate the fact that i just cant expresse myself english. What i wanted to say was that it should be transparent, not green. And, if the wallpaper is blue and the text is transparent, the text should be blue too. I Changed the wallpaper to be sure that you can understand now. Please, take a look at the i3 module and see the way it changes to the color of wallpaper. Now look at the xtittle, it still green.
![2016-10-30-033057_1920x1080_scrot](https://cloud.githubusercontent.com/assets/21113681/19834680/4b16a044-9e51-11e6-94d9-4100b5c3d27b.png)

**Comment by jaagr** [comment]
Ah I see, that's because of the font. I only fixed transparency for freetype fonts so far.

**Comment by jonathashenriques** [comment]
I tried with all my freetype fonts and i just cant get it working. Maybe i'm missing something.

**Comment by jaagr** [comment]
What fonts did you try? Tewi for example is a bitmap font.

**Comment by jonathashenriques** [comment]
Used all of the fonts of the "fc-list | cut -d ' ' -f2 | sort -u".

**Comment by jaagr** [comment]
Could you link the list.

**Comment by jonathashenriques** [comment]
Sure: 

> AvantGarde
C059:style=Bold
C059:style=Italic
C059:style=Roman
Cantarell:style=Bold
Cantarell:style=BoldOblique
Cantarell:style=Oblique
Cantarell:style=Regular
Clean:style=Regular
ClearlyU
ClearlyU:style=Regular
cursor.pcf:style=Regular
D050000L:style=Regular
deccurs.pcf:style=Regular
decsess.pcf:style=Regular
DejaVu
East
Estrangelo
Fixed:style=Bold
Fixed:style=ja
Fixed:style=ko
Fixed:style=Oblique
Fixed:style=Regular
Fixed:style=SemiCondensed
FontAwesome:style=Regular
FZChaoCuHei\-M10,方正超粗黑_GBK:style=Regular
FZFangSong\-Z02,方正仿宋_GBK:style=Regular
FZHei\-B01,方正黑体_GBK:style=Regular
FZKai\-Z03,方正楷体_GBK:style=Regular
FZLiShu\-S01,方正隶书_GBK:style=Regular
FZShuSong\-Z01,方正书宋_GBK:style=Regular
FZSongS\-Extended(SIP),方正宋体S\-超大字符集(SIP):style=Regular
FZSongS\-Extended,方正宋体S\-超大字符集:style=Regular
FZWeiBei\-S03,方正魏碑_GBK:style=Regular
FZXiaoBiaoSong\-B05,方正小标宋_GBK:style=Regular
FZXiHeiI\-Z08,方正细黑一_GBK:style=Regular
FZXingKai\-S04,方正行楷_GBK:style=Regular
FZYaoTi\-M06,方正姚体_GBK:style=Regular
GE
Goha\-Tibeb
Inconsolata:style=Bold
Inconsolata:style=Regular
Material
Meslo
micro.pcf:style=Regular
Newspaper:style=Regular
Nimbus
NimbusSans:style=Bold
NimbusSans:style=Oblique
P052:style=Bold
P052:style=Italic
P052:style=Roman
Roboto,Roboto
Roboto:style=Bold
Roboto:style=Italic
Roboto:style=Regular
Serto
Siji:style=Regular
Standard
Terminus:style=Bold
Terminus:style=Regular
tewi2a:style=Bold
tewi2a:style=Regular
tewifw:style=Bold
tewifw:style=double-wide
tewii:style=Bold
tewii:style=Regular
tewi:style=Bold
tewi:style=Regular
Ubuntu:style=Regular,Normal,Standard,Normaali,Normale,Standaard,Normalny,Arrunta
URW
Z003:style=Medium

**Comment by jaagr** [comment]
Try now

**Comment by jonathashenriques** [comment]
WOW, now spotify and clock are working with rgba colors too !!! YOU ARE AWESOME !!!! Almost everything is working now, just label-volume and xtitle. Any guess ? 
![2016-10-30-045538_1920x1080_scrot](https://cloud.githubusercontent.com/assets/21113681/19834955/21356100-9e5d-11e6-830f-cbc6b037e8ab.png)

**Comment by jaagr** [comment]
Great! Hm. And they are using freetype fonts?

**Comment by jonathashenriques** [comment]
Yeah ! Can i specify a font to an specific module ?

**Comment by jaagr** [comment]
Could you just test with my latest commit. The alpha channel was wrong.

**Comment by jonathashenriques** [comment]
Tested, sadly no changes. Idk why.

**Comment by jaagr** [comment]
You can specify the `format-font = <font-index>` property.

**Comment by jaagr** [comment]
Also try to remove the Siji font to see if it related to having an X font loaded.

**Comment by jonathashenriques** [comment]
I removed Siji, but it persists. The same thing happens to they, the alpha channel is setting the opacity and not the transparency.

**Comment by jonathashenriques** [comment]
I think that i found something. Looks like if i set the rgba color to something like #99f2f2f2 or #990d0d0d, the Spotify module or the clock module works just fine. But, if set a color with a high transparency ratio, like #0d000000, they do not work.

**Comment by jonathashenriques** [comment]
Sorry about the question but, are you going to give up ? It looks really hard to fix.

**Comment by jaagr** [comment]
We need to specify better how it should work... what the expected result is etc when using different colors... should the color blend with the bar background or should it burn through..

**Comment by jonathashenriques** [comment]
It should work like the i3 module. The text should be completely transparent if setted. The problem actually is only that the alpha bit is setting the opacity and not transparency. Images for a better example : 
![maxresdefault](https://cloud.githubusercontent.com/assets/21113681/19980997/3376a0da-a1e7-11e6-9036-cccbd5ec990d.jpg)

![photoshop-transparent-type](https://cloud.githubusercontent.com/assets/21113681/19981031/5c0ebd20-a1e7-11e6-9bba-af8e7a9a0c5b.jpg)

**Comment by jaagr** [comment]
This is no plain alpha blend and it would require compsiting. Plain X fonts render like that by default because they replace the existing pixels (currently being premuled).

**Comment by jonathashenriques** [comment]
OK, so the plan is to make the text blend with bar background now ?

**Comment by jaagr** [comment]
at least to me it's the most natural default.... but we could just make it a setting if we find a way to make make the xft glyphs replace the background pixels..

**Comment by jaagr** [comment]
This is now possible using the new rendering.. for example:

~~~ dosini
[settings]
compositing-background = over
compositing-foreground = xor
~~~

**NOTE:** only freetype fonts are supported now
