### ISSUE TITLE
Support ubuntu 12.04

### ISSUE THREAD

**Issue by jaagr** [jaagr/lemonbuddy#12]
Patch `utils/xlib.cpp` to work with an older version of xrandr.

**Comment by deadc0de6** [comment]
I guess this is related to that "older" version of xrandr ?

Compiling version 1.2.0 on debian 8 (jessie) fails with:
```
/home/test/tools/lemonbuddy/src/utils/xlib.cpp: In function ‘std::vector<std::unique_ptr<xlib::Monitor> > xlib::get_sorted_monitorlist()’:
/home/test/tools/lemonbuddy/src/utils/xlib.cpp:24:5: error: ‘XRRMonitorInfo’ was not declared in this scope
     XRRMonitorInfo *info = XRRGetMonitors(display, root, 1, &n_monitors);
     ^
/home/test/tools/lemonbuddy/src/utils/xlib.cpp:24:21: error: ‘info’ was not declared in this scope
     XRRMonitorInfo *info = XRRGetMonitors(display, root, 1, &n_monitors);
                     ^
/home/test/tools/lemonbuddy/src/utils/xlib.cpp:24:72: error: ‘XRRGetMonitors’ was not declared in this scope
     XRRMonitorInfo *info = XRRGetMonitors(display, root, 1, &n_monitors);
                                                                        ^
CMakeFiles/lemonbuddy.dir/build.make:790: recipe for target 'CMakeFiles/lemonbuddy.dir/src/utils/xlib.cpp.o' failed
make[2]: *** [CMakeFiles/lemonbuddy.dir/src/utils/xlib.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/lemonbuddy.dir/all' failed
make[1]: *** [CMakeFiles/lemonbuddy.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jaagr** [comment]
Yes exactly. I haven't looked into it yet, so the easiest fix at the moment is to upgrade xrandr.

**Comment by jaagr** [comment]
If you find a solution for this issue I'd appreciate if you report back! :)

**Comment by deadc0de6** [comment]
Well it won't help much but "Monitors" were introduced entirely in [1.5 of xrandr](https://cgit.freedesktop.org/xorg/lib/libXrandr/commit/?id=4437436906cbba5121115e552d564262e8b4c784)

Debian stable is currently running 1.4.2 (probably similar to what ubuntu 12.04 is running). Debian testing however has libxrandr-dev version 1.5 (haven't tested it though).

**Comment by jaagr** [comment]
Thanks for the information. What do you think about adding a compile option that would include the monitor changes as a fallback?

**Comment by deadc0de6** [comment]
Not sure to catch what you mean. But a fallback sounds good to me, it's always better than a compilation error. Sorry I won't be of much help here ;-)
