### ISSUE TITLE
Add ability to have multiple workspaces on a single bar in multi monitor setup

### ISSUE THREAD

**Issue by warmwaffles** [jaagr/lemonbuddy#122]
From this conversation: https://www.reddit.com/r/unixporn/comments/57g6wp/bspwm_lemonbuddy_my_current_setup/d94wrke/

I have a triple monitor setup. Each bar represents its own workspace. It would be nice to have that all on one bar. Lemonbar already accomplishes this.

**Comment by jaagr** [comment]
Add `label-output` or `label-monitor` that will be used to output the monitor name.

**Comment by jaagr** [comment]
How would the content be formatted? I'm guessing something like:

`monitor-1 workspace workspace workspace monitor-2 workspace workspace workspace`

**Comment by jaagr** [comment]
Would probably be good to use the same option as the i3 module to set the behavior: `pin-workspaces = true|false`

**Comment by warmwaffles** [comment]
> `monitor-1 workspace workspace workspace monitor-2 workspace workspace workspace`

This is perfectly fine with me. Just concatenate them.

**Comment by jaagr** [comment]
This was added in 5f21d7d44024d59869b926b8049710c281e86a37
