### ISSUE TITLE
Custom script with colored output

### ISSUE THREAD

**Issue by torresomar** [jaagr/lemonbuddy#124]
Hi, this is not an issue but a question, an apology in advance if this is a newbie question but it is my first time running Arch. I have a custom script which outputs the status of certain services I want to keep track of. Is it possible to use the output to format the lemonbuddy bar output? For example: 
I have a script that checks the status of the Docker service, if the service is active and running my script outputs "Docker Up". I want to know if lemonbuddy allows formatting based on that, so I would be able just to render a icon with different color to show the status of the service.

**Comment by jaagr** [comment]
Yeah, you can use the same formatting tags as lemonbar.

~~~
%{F#f00 B#000} red on black %{F#000 B#33d} black on blue %{F- B-} default
~~~

**Comment by jaagr** [comment]
Also had an idea about using different format tags depending on script exit code, but that's for a rainy sunday I guess :-)

**Comment by jaagr** [comment]
Closing this, please create a new ticket if you have any other issues/questions.

**Comment by torresomar** [comment]
Thanks, works like a charm!
