### ISSUE TITLE
Tray transparency

### ISSUE THREAD

**Issue by ashleymcdonald** [jaagr/lemonbuddy#125]
Not sure if its implemented but does the tray have transparency / match the background of the bar; If not then mine has a solid black background

**Comment by jaagr** [comment]
It's supposed to inherit the bar's background, but I haven't tested it enough to know for sure. Will take a look when I have time.

**Comment by ashleymcdonald** [comment]
No stress. I'm going back to stalonetray so I can position it to the left of my right modules. 😋
Back to scripts to fix layering on full screen 😔

**Comment by jaagr** [comment]
It is now possible to specify a custom background color. The tray container can alos be centered. [See the wiki for the new settings](https://github.com/jaagr/lemonbuddy/wiki/Configuration).

**Comment by jonathashenriques** [comment]
Any guess ?
![2016-10-31-220650_1920x1080_scrot](https://cloud.githubusercontent.com/assets/21113681/19875757/b6c515f8-9fb6-11e6-8da5-324fa4185a20.jpg)

**Comment by jaagr** [comment]
@jonathashenriques for now, you will have to manually define a matching color using `tray-background = ...`

**Comment by jonathashenriques** [comment]
I setted tray-background to #991a1a1a but, some parts of the background are not getting the right color. Take a look at dropbox icon, for an example.

**Comment by jaagr** [comment]
Try to not set the alpha bits. For example only: #2ABBFF

**Comment by jonathashenriques** [comment]
Without yhe alpha bits, it's working :/

**Comment by Slimior** [comment]
Why is this issue closed? It still is very visible.

Background color of tray does parse correctly, even with transparency bits, however the pixels do not blend with pixels behind tray (wallpaper for example) but with black.
i.e. setting `tray-background = #88FF0000` produces dark red, as layer of red at half opacity is imposed on black background.

Lemonbuddy version: 2.1.11
with Compton version: 0.1~beta2
on top of i3-gaps version: 4.12

**Comment by kimalekst** [comment]
Sure this error is closed? Experiencing the mentioned error.
In addition when i set the bar background to #00000000, the bar becomes black as mentioned. But the tray becomes transparent.
polybar 3.4.0
i3 4.17
Setting desktop background with feh.

**Comment by patrick96** [comment]
@kimalekst This is not related to this issue. The transparency implementation for the tray has since changed drastically. The tray now always uses pseudo-transparency while the bar by default needs a compositor for transparency. It seems you are not running a compositor, that's why your bar is black (the alpha byte of `#00000000` is ignored) but the tray does use the alpha byte. Set `pseudo-transparency = true` in the `[settings]` section.
