### ISSUE TITLE
i3 workspace name stripping

### ISSUE THREAD

**Issue by 97-109-107** [jaagr/lemonbuddy#126]
When using:

```
strip-wsnumbers = true
```

For the internal/i3 module, given i3 workspaces called:

```
1: www
2: vim
3: term
...
```

The function yields names ' www', ' vim', ' term' (not the leading space). The i3 docs don't seem to be clear about the naming convention of numbered workspaces. Looking at the [function](https://github.com/jaagr/lemonbuddy/blob/e239140db7a0fbc0d835e285c9e8d7f664e5ecbc/include/modules/i3.hpp#L163:) - could we introduce an option to trim leading whitespace?

**Comment by jaagr** [comment]
Yeah... don't think we need an option for it though, might as well trim by default. If someone wants to add spaces for some reason they can use `label-spacing = N`
