### ISSUE TITLE
bspwm module - workspace name/icon not showing up

### ISSUE THREAD

**Issue by malynome** [jaagr/lemonbuddy#128]
Hi, I'm trying to setup a bar with the bspwm module displaying my different workspaces, but the icons defined with ws-icon-[1-9] aren't being shown, its just a blank space, although with the formatting(foreground, background color etc.). I've determined that it isn't the font, as the icons can show up in other modules. I've followed the wiki and the example bars, here's the module code:
```
[module/bspwm]
type = `internal/bspwm`
ws-icon-0 = yi;一
ws-icon-1 = er;二
ws-icon-2 = san;三
ws-icon-3 = si;四
ws-icon-4 = wu;五
ws-icon-5 = liao;六
ws-icon-6 = chi;七
ws-icon-7 = ba;八
ws-icon-8 = jiao;九

label-active = %icon%
label-active-foreground = #ffffff
label-active-background = #3f3f3f
label-active-underline= #fba922
label-active-padding = 2

label-occupied = %icon%
label-occupied-underline = #555555
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-background = #bd2c40
label-urgent-foreground = #000000
label-urgent-underline = #9b0a20
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = #444
label-empty-padding = 2
```

It's probably just me that doesn't understand something, but if you could point me in the right direction, I would be most grateful.
Best regards

**Comment by jaagr** [comment]
Hi. The configuration looks good. Make sure you use the same workspace names as defined in bspwm. You could also add a fallback icon using 

~~~dosini
ws-icon-default = ...
~~~

**Comment by malynome** [comment]
Ahh, didn't realise they workspace names had to be the same in bspwm and in the bar, my mistake!
But thanks alot, I really like the bar, it's been a breeze using it so far. Now, I don't know if I'm the only one to be making this mistake, but it might be worth adding this info to the wiki.

**Comment by jaagr** [comment]
Yeah I will add it to the wiki. Please report any other issues you may encounter.
