### ISSUE TITLE
Could NOT find Threads

### ISSUE THREAD

**Issue by Dr-Terrible** [jaagr/lemonbuddy#129]
While compiling v2.1.1 I got this CMake error during the configure phase:

> -- The CXX compiler identification is Clang 3.8.1
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/x86_64-pc-linux-gnu-pkg-config (found version "0.28") 
-- liblemonbuddy_static
-- Boost version: 1.56.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:43 (find_package)

The error is legit, CMake's macros for detecting `pthread` make use of `C` code, not `C++`.

The solution is trivial, you just need to add the missing "C" to the project directive in CMakeLists.txt as well explained here: http://stackoverflow.com/questions/15193785/how-to-get-cmake-to-recognize-pthread-on-ubuntu

I manually added the missing C and the issue is gone:

> -- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/x86_64-pc-linux-gnu-pkg-config (found version "0.28") 
-- liblemonbuddy_static
-- Boost version: 1.56.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.7.0") 
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found X11_XCB: /usr/lib64/libX11-xcb.so  
-- Checking for module 'fontconfig'
--   Found fontconfig, version 2.12.1
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.12
-- Found PythonInterp: /var/tmp/portage/x11-misc/lemonbuddy-2.1.1/temp/python2.7/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib64/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib64/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib64/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib64/libxcb-util.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib64/python2.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-randr.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xproto.xml
-- Found ALSA: /usr/lib64/libasound.so (found version "1.0.29") 
-- Found Libiw: /lib64/libiw.so  
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /var/tmp/portage/x11-misc/lemonbuddy-2.1.1/temp/python2.7/bin/python (found suitable version "2.7.12", minimum required is "2.6")

**Comment by jaagr** [comment]
What version of cmake are you using? The c limitation for FindThreads.cmake are gone for newer releases.

But it would be a good idea to add it to also support older versions.

**Comment by Dr-Terrible** [comment]
> What version of cmake are you using?

CMake 3.6.2

> But it would be a good idea to add it to also support older versions.

I forgot to mention that I'm using GNU/Linux and not MacOS. At the moment, CMake v3.4.x-3.5.x is the usual stable version installed on common Linux distros (so far, I checked Gentoo, Debian, Ubuntu, Arch); so yes, it's definitively a good idea to add "C" to support old CMake versions.

**Comment by hthuong09** [comment]
Are you using Arch Linux? If yes then try [clang 3.5](https://www.archlinux.org/packages/extra/x86_64/clang35/) instead of latest 3.8.1
I had that issue too when try to compile it manually,  then I try [aur version](https://aur.archlinux.org/packages/lemonbuddy-git) and realized it use different clang version with mine.
