### ISSUE TITLE
MPD module can not run

### ISSUE THREAD

**Issue by hthuong09** [jaagr/lemonbuddy#13]
I use the default config in your bspwm.conf for mpd module

```
[module/mpd]
type = internal/mpd
clickable_progress = true
format:online = <icon:prev> <icon:stop> <toggle> <icon:next>  <icon:repeat> <icon:random>  <bar:progress> <label:time>  <label:song>

icon:play = 
icon:pause = 
icon:stop = 
icon:prev = 
icon:next = 
icon:random = 
icon:repeat = 

toggle_on:foreground =
toggle_off:foreground = #55

bar:progress:width = 45
bar:progress:indicator = |
bar:progress:indicator:foreground = #ff
bar:progress:indicator:font = 3
bar:progress:fill = ─
bar:progress:fill:foreground = #bb
bar:progress:fill:font = 3
bar:progress:empty = ─
bar:progress:empty:font = 3
bar:progress:empty:foreground = #44
```

I run fine without mpd module. Every time I try add mpd module to the bar, it crash and the bar didn't show up.

Here is a little information I can give you.
```
┌─╼ [ ~/b/testlmbd ]
└────╼ ./lemonbuddy_wrapper.sh top                                                                                                     [7:26:58 PM] 
debug ** Entering STAGE 1
info  ** Starting event loop...
debug ** Entering STAGE 2
debug ** Loading modules
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
./lemonbuddy_wrapper.sh: line 40:  5902 Aborted                 (core dumped) lemonbuddy "$@" -p "$pipe" --log=debug
```

Tell me if you need more information.

**Comment by jaagr** [comment]
Hi! Thanks for reporting the issue. What version are you using?

**Comment by hthuong09** [comment]
I use this version: https://aur.archlinux.org/packages/lemonbuddy/

**Comment by jaagr** [comment]
Could you try post the output of:

    $ lemonbuddy top -l trace

**Comment by hthuong09** [comment]
Here is output: https://gist.github.com/hthuong09/f93764006e3fe4b10edd441ff0af5253

**Comment by hthuong09** [comment]
I tried install the git version. At first, I can start it with mpd. It was running for some minute until I click "next song" in the panel. It crashed and I can't start it again.

**Comment by jaagr** [comment]
Could you post the full configuration file that you are using?

**Comment by hthuong09** [comment]
Here is my config file: https://gist.github.com/hthuong09/161f6b6d556ab3d0699ba7d14d4b5f1f

**Comment by jaagr** [comment]
I'm not really sure where the error happens but I fixed a few things. Could you update your git version and try again? I tested your config on my arch installation and it worked fine.

**Comment by hthuong09** [comment]
I updated. It seems work fine. 
I will update if there is any problem occur.
Thank you.

**Comment by jaagr** [comment]
OK great. I think it was caused by this: https://github.com/jaagr/lemonbuddy/commit/89a476e94c186a972a09d2f22ff96a7bab621aa3#diff-028e1e7e3c9d24967229aaa5fdd183faR380

**Comment by hthuong09** [comment]
Probably, because many song of my playlist missing artist or album.
