### ISSUE TITLE
Tray pushes modules out of view

### ISSUE THREAD

**Issue by ashleymcdonald** [jaagr/lemonbuddy#130]
Sometimes when the tray expands to allow for new icons the left of the right modules get clipped. I'll work on a reliable way to relocate and post back

Modules used were CPU and memory with tray on right. With CPU having the label "CPU" the "c" is not visible when it expands by 1icon then the "P" when another appears etc.

**Comment by ashleymcdonald** [comment]
Relocate= replicate the issue

**Comment by jaagr** [comment]
This could be fixed since I cleaned up the tray and fixed some minor stuff.. Are you able to reproduce it?

**Comment by ashleymcdonald** [comment]
After the update have not seen it happen. To make it happen required restarting the bars and it may have been a conpton issue. Will re open if I come across it again. Cheers
