### ISSUE TITLE
Lemonbuddy crashed on click of a custom script.

### ISSUE THREAD

**Issue by contactgsuraj** [jaagr/lemonbuddy#131]
I have a custom scrip as follows

[module/dropbox]                                                                        
type = custom/script
exec = echo "%{A1:command}`script`%{A}"
format-underline = #458588
interval=10

Clicking on this crashes lemonbuddy, after which killing it is the only option.

**Comment by jaagr** [comment]
Can you post your full config

**Comment by contactgsuraj** [comment]
Sure thing. This is a tiny script I wrote to indicate the status of dropbox

~~~
#!/bin/bash
#Dropbox Status outputs
#Dropbox isn't enabled : "Dropbox"
#Dropbox is startin: "Starting..."
#Dropbox is Syncing: "Syncing ..."
#Dropbox is running: "Up to date..."
STATUS="$(echo `dropbox status` | awk '{print $1;}')"
C_status=#fbf1c7
DROPBOX_ICON=""
if [[ $STATUS == *"Dropbox"* ]]; then
  C_status=#fb4934
elif [[ $STATUS == *"Starting"* ]]; then
  #statements
  ICON=
elif [[ $STATUS == *"Syncing"* ]]; then
  DROPBOX_ICON=
else
  I=1
fi
echo "%{F$C_status}$DROPBOX_ICON%{F}$ICON"
#echo "%{A:dropbox start}$DROPBOX_ICON $ICON%{A}"
~~~

The commented echo is what crashes the bar, and I intended on making the click action on the icon one that triggers dropbox

The module in my lemonbuddy config is as follows.

~~~
[module/dropbox]
type = custom/script
exec = echo "`~/github/Scripts/dropboxStatus.sh`"
format-underline = #458588
interval=5
~~~

As a side note, I think the wiki should have something about clickable buttons, I am completely new to this so I am horrendously lost.

**Comment by jaagr** [comment]
You are missing the closing colon of the %{A} tag. The correct syntax is:

~~~
%{A:command:}....%{A}
~~~

And also the foreground color reset should be:

~~~
%{F-}
~~~

You are right about the wiki. Input like this is really helpful since it's hard for me to know how it is for new users.

**Comment by jaagr** [comment]
Of course the invalid tags should not crash the bar so that will need to be fixed.

**Comment by jaagr** [comment]
I also want to add a hint about the button handlers available for the `custom/script` module. [Info on the wiki](https://github.com/jaagr/lemonbuddy/wiki/Module:-script#additional-formatting).

**Comment by contactgsuraj** [comment]
Now I've gone ahead and replaced the %{A} tags to the button handlers instead. Here is the code for it

~~~
#!/bin/bash
#Dropbox Status outputs
#Dropbox isn't enabled : "Dropbox"
#Dropbox is startin: "Starting..."
#Dropbox is Syncing: "Syncing ..."
#Dropbox is running: "Up to date..."
STATUS="$(echo `dropbox status` | awk '{print $1;}')"
C_status=#fbf1c7
DROPBOX_ICON=""
if [[ $STATUS == *"Dropbox"* ]]; then
  C_status=#ec644b
elif [[ $STATUS == *"Starting"* ]]; then
  #statements
  ICON=
elif [[ $STATUS == *"Syncing"* ]]; then
  DROPBOX_ICON=
else
  I=1
fi
echo "%{F$C_status}$DROPBOX_ICON%{-F} $ICON"
~~~

The module in lemonbar's config file looks as follows
~~~

[module/dropbox]
type = custom/script
exec = ~/github/Scripts/dropboxStatus.sh
format-underline = #458588
click-left = dropbox start
interval=2
format-padding = 2
~~~

The bar still crashes on a click.

**Comment by jaagr** [comment]
I will test the script and get back to you

**Comment by jaagr** [comment]
Try replace `I=1` in the else with `exit`. Fixes it for me.

I don't know why the bar hangs, but but I'll look into it.

**Comment by contactgsuraj** [comment]
The whole script works fine as it is, dropbox launches accordingly, but the bar crashes and does not update any further. Thanks for looking into this

**Comment by jaagr** [comment]
I found a bug that caused the execution to be blocked while the sub process was running. Please verify that it's fixed.

**Comment by contactgsuraj** [comment]
Whew! Works like a charm now!

**Comment by jaagr** [comment]
Great! Please report any other issues you encounter.

**Comment by blackbart420** [comment]
Any chance you integrate this module ?

**Comment by jaagr** [comment]
@blackbart420 it's a `custom/script` so you can use whatever @g-suraj posted here.
