### ISSUE TITLE
Volume module stopped working

### ISSUE THREAD

**Issue by omrisim210** [jaagr/lemonbuddy#133]
![image](https://cloud.githubusercontent.com/assets/13455401/19810778/73737a5a-9d37-11e6-863a-3a7c7c17b176.png)

I decided to open a new issue for this problem

The volume module worked fine up until a few days ago and now (after upgrading to the latest version) it just stopped working

Here's the config for the module:

```
[module/volume]
type = internal/volume

format-volume = <ramp-volume> <label-volume> <bar-volume>
label-volume = %percentage%

bar-volume-width = 10
bar-volume-foreground = #aaff77
bar-volume-indicator = ▓
bar-volume-indicator-font = 6
bar-volume-fill = ▒
bar-volume-fill-font = 6
bar-volume-fill-font-style = bold
bar-volume-empty = ░
bar-volume-empty-font = 6

format-muted = <label-muted>
label-muted =    muted   ░░░░░░░░░░
label-muted-foreground = #66

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
```

I've always used pulseaudio

Is it possible to get it to work again and/or will PA support be added to lemonbuddy?

**Comment by jaagr** [comment]
If it worked before it should work now. What's the output of:

~~~
$ amixer scontrols
~~~

**Comment by omrisim210** [comment]
```
$ amixer scontrols
Simple mixer control 'Mic',0

```

Hmm..

**Comment by jaagr** [comment]
The module won't work without a valid master mixer.

**Comment by omrisim210** [comment]
Would you mind elaborating?

**Comment by jaagr** [comment]
You would need to troubleshoot your alsa setup. What modules do you have loaded? `lsmod | grep snd`

**Comment by omrisim210** [comment]
[this](http://www.alsa-project.org/db/?f=b6598cc2e078e82fb8d3d8cc5312ad768e4e8a9a) is the output of `alsa-info.sh`

**Comment by jaagr** [comment]
Add this to `/etc/asound.etc` and it should work.

~~~
defaults.pcm.card 1
~~~

**Comment by jaagr** [comment]
Closing for now, please re-open if you still have issues with the module.

**Comment by gatlinnewhouse** [comment]
I have a similar issue here as well. However adding that line to my `/etc/asound.etc` did not help.

``[this](http://www.alsa-project.org/db/?f=3f33911aa7c41bd68497b2842bfc12600a793d3e) is the output of `alsa-info.sh`

**Comment by jaagr** [comment]
@gatlinnewhouse Try to explicitly set the soundcard to be used by defining:

~~~ dosini
# For example `hw:1`
master-soundcard = hw:1
speaker-soundcard = hw:1
headphone-soundcard = hw:1
~~~

**Comment by gatlinnewhouse** [comment]
I found a different fix!

I used `asoundconf` to set the default audio output to pulseaudio!
