### ISSUE TITLE
No bar showing up with example config, bar output appears to be shown in terminal.

### ISSUE THREAD

**Issue by hooolius** [jaagr/lemonbuddy#134]
I installed Lemonbuddy on my system (Void Linux) using the package manager. I also made sure to manually install all the dependencies listed here on Github.  Whenever I try to start a bar, the output seems to just go in the terminal, with nothing showing up on the screen. Here's what it looks like:
![lemonbar](https://cloud.githubusercontent.com/assets/16958591/19824950/261666e0-9d74-11e6-8eb1-abd4239d8a8c.png)

What might be causing this?

**Comment by jaagr** [comment]
The version available in the xbps repository is old. You will have to build it manually until I've updated the package.

**Comment by jaagr** [comment]
Closing, please create another ticket if you encounter any issues.

**Comment by jaagr** [comment]
I've submitted a pull-request to update the package: https://github.com/voidlinux/void-packages/pull/5075

**Comment by hooolius** [comment]
> I've submitted a pull-request to update the package: voidlinux/void-packages#5075

Awesome, thank you.

**Comment by jaagr** [comment]
Please report any issues you bump into
