### ISSUE TITLE
Colored output for scripts not working

### ISSUE THREAD

**Issue by leohahn** [jaagr/lemonbuddy#135]
I am using this script to show how many packages are available for update:

```bash
#!/bin/bash

NUMBER_PKGS=$(pacaur -Qu | wc -l)
RED='\033[0;31m'

if [ "$NUMBER_PKGS" -eq 0 ]
then
  echo ""
else
  echo "${RED} $NUMBER_PKGS"
fi
```
This works fine on the terminal, but it does not on the bar.

here is the module:
```conf
[module/pkg-updates]
type = custom/script
exec = /home/lhahn/.config/lemonbuddy/scripts/check-pkg-updates.sh
interval = 60
```

**Comment by jaagr** [comment]
There's currently no support for ansi colors. Formatting tags are supported.. try:

- `echo "%{F#f00} $NUMBER_PKGS%{F-}"`

**Comment by leohahn** [comment]
Thanks, that works.

**Comment by jaagr** [comment]
There's some info about the tags in the wiki... Please report any other issues you encounter
