### ISSUE TITLE
Assertion Failed error

### ISSUE THREAD

**Issue by zacknorman** [jaagr/lemonbuddy#137]
Not sure if this is a bug or if I'm an idiot; Almost every module in my config file breaks the lemonbuddy bar (battery, volume, memory), but not date or workspace or mpd.

The error I get before it fails:
```
lemonbuddy: /home/oz0ne/lemonbuddy/include/modules/meta.hpp:182: lemonbuddy::v2_0_0::modules::module<Impl>::~module() [with Impl = lemonbuddy::v2_0_0::modules::battery_module]: Assertion `!running()' failed.
Aborted (core dumped)
```
Sorry for another issue, but I'd like to get this up n running on my system

**Comment by jaagr** [comment]
I've fixed that bug, but i see now I didn't create a patch release so it's only in the git packages. Hold on and I'll push a tag.

**Comment by zacknorman** [comment]
Cheers jaagr

**Comment by jaagr** [comment]
There, version `2.1.11` is now available.
