### ISSUE TITLE
Padding / Module Margin not working

### ISSUE THREAD

**Issue by BenoitAverty** [jaagr/lemonbuddy#138]
Hi,
I have pretty much finished my bar configuration but I'm not completely happy about the layout of the bar.

I noticed that the settings padding-left / padding-right don't seem to have any effect, nor do the module-margin-right / module-margin-left settings.

Here is a screenshot with both "padding" settings set to 5 : 
![2016-11-01-094700_1920x1080_scrot](https://cloud.githubusercontent.com/assets/17006335/19884524/640c8d6e-a01a-11e6-99c3-873fd34a74ff.png)

Thanks in advance

**Comment by jaagr** [comment]
Hi, could you please post your full configuration.

**Comment by BenoitAverty** [comment]
Here it is : https://github.com/BenoitAverty/dotfiles/blob/82e3e6a20879e324067de4a45f4ab8bd6ec0ff47/.config/lemonbuddy/config
I'm not sure if it corresponds exactly to the screenshot above but i'm certain there was never any padding for the bar.

**Comment by jaagr** [comment]
Rename the properties and you should be good to go:

`padding_left` -> `padding-left`
`padding_right` -> `padding-right`

**Comment by BenoitAverty** [comment]
Wow, I feel a little bit dumb right now !

Thanks :smile:
