### ISSUE TITLE
Add cli option to specify monitor to show

### ISSUE THREAD

**Issue by edgard** [jaagr/lemonbuddy#139]
The idea is to emulate the same behavior of "monitor=" on the config file so we can dynamically assign bars during our startup script.

**Comment by BenoitAverty** [comment]
You can do this using env vars. Set an environment variable and use ${env:VARIABLE_NAME} in the lemonbuddy config.

**Comment by edgard** [comment]
ah yeah, of course. my bad. closing. thanks. :D

**Comment by jaagr** [comment]
Hint.. you can also define a temporary variable when launching the bar:

`MY_VAR=value lemonbuddy mybar` and reference it with  `${env:MY_VAR}`
