### ISSUE TITLE
Center module background override bar background

### ISSUE THREAD

**Issue by SuperBo** [jaagr/lemonbuddy#141]
My bar background is grey, but after the center date module, my bar background is reset to same background as my center module.

http://imgur.com/a/InGP5

**Comment by jaagr** [comment]
hi @SuperBo could you please post your full configuration

**Comment by SuperBo** [comment]
This is my config.

[config.txt](https://github.com/jaagr/lemonbuddy/files/571186/config.txt)

**Comment by jaagr** [comment]
I found the bug, and just pushed a fix. Available in the -git package.
