### ISSUE TITLE
Battery module stopped working

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/lemonbuddy#142]
With the two latest versions battery module just stops refreshing after some time.

Right now I have 55.3 percent left, while lemonbuddy still shows 61.

It shows the correct percentage after the laptop comes out of sleep.

**Comment by sconos** [comment]
I can't link it, but this should be the same issue as #140, maybe reopen the already existing one

**Comment by Vintodrimmer** [comment]
Didn't notice, sorry.
