### ISSUE TITLE
Multiple Interfaces in wifi/ethernet

### ISSUE THREAD

**Issue by SageEx** [jaagr/lemonbuddy#144]
Hi, in the wifi module, we are required to give one interface.
For ethernet, I don't want to make a new module.

I'm just interested in knowing the total download and upload speed.

Would it be possible to see the speed from multiple interfaces (except lo) combined ?

**Comment by jaagr** [comment]
Hi, yeah that's doable.. the module is already iterating all interfaces when querying packet stats.

**Comment by SageEx** [comment]
Thanks :)
