### ISSUE TITLE
Cannot parse empty color on the latest version 2.15

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/lemonbuddy#145]
After update (from 2.1.12) 2 out of my 3 panels stopped working with the error 

> error: Failed to setup bar renderer: Cannot parse empty color

the config didn't change and [here it is](https://paste.pound-python.org/show/rz57ZQobWE9Wx1RXFEPa/). Left panel works OK, middle and right don't,

**Comment by jaagr** [comment]
The parameters `linecolor` and `border-color` are empty for those bars. Remove or comment and you should be good.

**Comment by jaagr** [comment]
If you don't want to show the color, you can make it fully transparent by setting the value to `#00ffffff`

**Comment by Vintodrimmer** [comment]
Thank you!
