### ISSUE TITLE
tray not working in version 2.2.0

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/lemonbuddy#146]
I have tray enabled for the middle bar. It stopped working after the latest update.
```
Bars launched...
warn: Disabling tray manager (reason: disabled in config)
warn: Disabling tray manager (reason: disabled in config)
error: XCB_VALUE (2)
error: Cannot activate traymanager... failed to setup window
```
Windows manager is bspwm

**Comment by jaagr** [comment]
The build is also failing so I think it's because a missing dependency.. I will push a fix.

**Comment by Vintodrimmer** [comment]
Same error.

**Comment by jaagr** [comment]
Tried your config and got the same error... fix pushed

**Comment by Vintodrimmer** [comment]
Works now, thanks.
