### ISSUE TITLE
Battery charging animation display wrong

### ISSUE THREAD

**Issue by hthuong09** [jaagr/lemonbuddy#15]
It's not actually a bug, but I will just leave it here as a feature you might want to add
In some laptop the battery may drop below 100% but it's not charging.
For example, my current battery is 98% but it's not charging until it drops below 95%.
In my case the `acpi -b` command will be display as:
```
┌─╼ [ ~ ]
└────╼ acpi -b                                                                                                                                    
Battery 0: Unknown, 98%
```

**Comment by jaagr** [comment]
That's already implemented. Use this in your config `full_at = 98`

**Comment by hthuong09** [comment]
I looked a bit into the code. If I set `full_at = 95` whenever my battery level goes beyond 95. It will consider batter is 100 and charged? Even sometimes it actually charging when battery level is beyond 95?

**Comment by jaagr** [comment]
Yes, it will set it to 100% and set the state to FULL. The battery can of course keep charging but the bar will treat it as fully charged. The reason being that some batteries never charge more than N percent.
