### ISSUE TITLE
Battery info does not update

### ISSUE THREAD

**Issue by Henrijk** [jaagr/lemonbuddy#150]
Hey! I have two batteries in my laptop which I display using lemonbuddy.

In order for the status (percentage) to update I have to do a reload of i3wm using $mod+shift+R. It seems that it is the polling that does not function correctly. The polling interval that I've set is 5. How come it does not update? Should I set polling to a lower value or disable it entirely?

Here is my config:

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
poll-interval = 5

[module/battery2]
type = internal/battery
full-at = 99
battery = BAT1
adapter = AC
poll-interval = 5

**Comment by BenoitAverty** [comment]
Did you try the solutions described in #140? In particular, updating lemonbuddy.

**Comment by Henrijk** [comment]
Hey! My bad. It seems that I had not updated it. Just started using Arch and did not know how to update AUR packages.. Thanks!
