### ISSUE TITLE
i3 workspace moved from output still shows on bar

### ISSUE THREAD

**Issue by edgard** [jaagr/lemonbuddy#151]
So, on I3, if you move a workspace to a diferent output and back it doesn't update on the the "destination" bar, it is stuck there forever.

**Comment by jaagr** [comment]
I will test if the removal is reported via the ipc subscriber...

**Comment by edgard** [comment]
It's a weird problem, I can reproduce like this:

1) Move from output 1 to output 2 - updates on both bars. removes from bar 1 and shows on bar 2.
2) Move back from output 2 to output 1 - update bar 1 and shows it but bar 2 also still shows it.

**Comment by jaagr** [comment]
Are you using `pin-workspaces = true` ? Could you post your config. And how are you moving the output?

**Comment by jaagr** [comment]
Is this how you move the workspace? https://u.teknik.io/aGXkV.webm

**Comment by edgard** [comment]
Hey Michael! Here is the thing, actually, it's working now. Not sure if it was something related to the last updates (I use all from git, basically), or something I changed I am not aware of.

But yeah, I'm using pin-workspaces = true.

Here is my lemonbuddy config:
https://github.com/edgard/dotfiles/blob/master/config/lemonbuddy/config

And my i3 config:
https://github.com/edgard/dotfiles/blob/master/config/i3/config

And yes, i use move workspace to output xxxx to do it:
https://github.com/edgard/dotfiles/blob/master/config/i3/config#L94-L98

**Comment by jaagr** [comment]
I did some tweaks to the i3 module earlier. Now there's a small delay (25ms) between each event which might have solved the issue. I'll close the issue for now and we'll reopen it in case you bump in to the bug again.

I like how you stored the colors in your config by the way... should add it to the wiki.

**Comment by edgard** [comment]
great! let you know if happens again. thanks for the great work. :)
