### ISSUE TITLE
New project name

### ISSUE THREAD

**Issue by jaagr** [jaagr/lemonbuddy#161]
Been thinking about renaming the project since it makes no sense now when lemonbar isn't used.

Any suggestions?

**Comment by NBonaparte** [comment]
- Bartender
- Barista
- Limoncello

Probably aren't the best...

**Comment by l4ngl3y** [comment]
tilingbar )

**Comment by Quent42340** [comment]
- modulusbar
- flexbar
- ...

(to point out the modularity)

**Comment by beiro** [comment]
naranja(spanish word for orange), to keep it citric + jaa(from jaagr) = naranjaa :)

**Comment by Capuno** [comment]
**Mozilla Firefox**

**Comment by jaagr** [comment]
Thanks for the suggestions (though I think that one might be taken @Capuno). I was going for *flexbar* but the package name was taken in alot of repositories so I'm changing the name to *polybar*.
