### ISSUE TITLE
Keep i3 workspaces on the bar?

### ISSUE THREAD

**Issue by edgard** [jaagr/lemonbuddy#162]
Is there a way to keep the i3 workspaces showing all the time on the bar? Like bspwm does? Or is this a limitation on i3 ipc itself?

I tried disabling pin-workspaces but then it shows all workspaces on all monitors.

**Comment by jaagr** [comment]
Not that I know of, It's designed that way in i3. We could of course fake it, but those things tend to blow up on you :-)

**Comment by edgard** [comment]
Ah, no worries. If it was just a matter of simply exposing an internal structure, that would be a nice feature.

**Comment by jaagr** [comment]
I think the workspaces get destroyed when left empty, ie not just hidden. But I'm not sure

**Comment by edgard** [comment]
Not using i3 anymore, so, closing. :D
