### ISSUE TITLE
Add other states for bspwm dimmed desktops

### ISSUE THREAD

**Issue by edgard** [jaagr/lemonbuddy#165]
Hi Michael, one more idea. :D

On bspwm, you can configure overrides for dimmed desktop, however, it overrides any other state, including occupied, empty, urgent, etc. It would be nice if we could configure overriding dimmed granular to the other states. 

Use case:
On active monitor, I have a bar like [this](https://u.teknik.io/lSbWe.png) where active desktop have a blue overline and occupied ones have a gray overline.

However, if I want to make the dimmed desktops with a gray overline for occupied ones and no overline for empty, it's not possible at the moment (or I haven't figured out how?). If I override the overline color on dimmed, it applied to all desktops on that monitor.

**Comment by jaagr** [comment]
Yeah that's how it works at the moment. That's how I styled my bar when I wrote it so that's why. But yeah, it would be a nice thing to have.

**Comment by edgard** [comment]
ah, so, it wasn't just me goofing. :D nice to know. also, sorry for those issue opening lately. i really enjoy the project and would love to send some pr, but I have absolutely no experience with X/XCB programming. maybe in the future. :D

**Comment by edgard** [comment]
merged #167
