### ISSUE TITLE
Tray icon (nm-applet) disappearing on update of bar

### ISSUE THREAD

**Issue by Taros007** [jaagr/lemonbuddy#166]
First of all thank for all your work on this! 

Issue: nm-applet icon in tray disappears from the bar as soon as another module updates (in my case date updates every second and hence the icon diappears). This results in a flickering icon. However, when there is no window on my screen (aside from the bar), the icon doesn't appear at all anymore.

System: Arch, i3, compton, no DE
Config:  [click](https://ptpb.pw/2lLJ)

**Comment by jaagr** [comment]
Can't reproduce it. If you can, try removing src/component/bar.cpp @ 403 and see if it fixes the issue.

**Comment by jaagr** [comment]
Was able to reproduce the redraw flickering on my arch box. The referenced commit solves it.

**Comment by Taros007** [comment]
Awesome, thanks dev!
