### ISSUE TITLE
Ubuntu RANDR (VMware workstation)

### ISSUE THREAD

**Issue by rowlandwatkins** [jaagr/lemonbuddy#18]
Hi,

I compiled lemonbuddy as per instructions in the README, and get the following when attempting to run lemonbuddy_wrapper.sh example:

[[[
X Error of failed request: BadRequest (invalid request code or no such operation)
  Major opcode of failed request: 141 (RANDR)
  Minor opcode of failed request: 42 ()
  Serial number of failed request: 10
  Current serial number in the output stream: 10
]]] 

This appears to be related to RANDR:getMonitors. Under a VM, these will be listed as Virtual1.. Virtual8, I'm wondering if this is the problem. If so, then I guess I can get the monitor information by hand and populate the monitor list myself.

Environment:
Ubuntu 15.10, kernel 4.3.0 (opengl 3.3, confirmed with steam)
VMware Workstation 12

Any other hints would be most helpful!

Cheers,

Rowland

**Comment by jaagr** [comment]
Hi,

Could you post the relevant bar section in your config? If the monitor parameter is set to a valid output, it should work.

**Comment by rowlandwatkins** [comment]
Hi @jaagr, 

I used the following:
https://github.com/jaagr/lemonbuddy/blob/master/examples/config

After I received the first BadRequesr error, I stripped down my config to only the [bar/example] section, which didn't help.

This example doesn't appear to have any reference to a monitor parameter - is this documented elsewhere?

Thanks,

Rowland

**Comment by rowlandwatkins** [comment]
OK, digging further, my VM doesn't return any EDID monitor name, which is probably why X has a fit when asked to getMonitors(). I we only need to set the monitor parameters, then I'll add to the config file to get them instead.

**Comment by rowlandwatkins** [comment]
Cool, setting the monitor through the config allows the example to work now :)

**Comment by jaagr** [comment]
Great! I will make sure to add the bar section to the documentation.

Thanks for the thorough report, it's much appreciated.
