### ISSUE TITLE
Both AUR and git build fail on Arch Linux 4.5.4

### ISSUE THREAD

**Issue by NateBrune** [jaagr/lemonbuddy#2]
$ git submodule update --init --recursive
```
fatal: Not a git repository: /home/myusername/lemonbuddy/.git/modules/contrib/i3ipcpp
Unable to find current revision in submodule path 'i3ipcpp'
```
$yaourt -A lemonbuddy
```
   used as include directory in directory /tmp/yaourt-tmp-newton/aur-lemonbuddy/src/lemonbuddy/contrib/i3ipcpp/3rd/jsoncpp/include
   used as include directory in directory /tmp/yaourt-tmp-newton/aur-lemonbuddy/src/lemonbuddy/contrib/i3ipcpp/3rd/jsoncpp/include

-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-newton/aur-lemonbuddy/src/lemonbuddy/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/yaourt-tmp-newton/aur-lemonbuddy/src/lemonbuddy/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build lemonbuddy.
==> Restart building lemonbuddy ? [y/N]
```

I am fairly sure that I have all the dependencies required. Thanks this looks like a really cool project.

**Comment by NateBrune** [comment]
I traced it down to a dependency issue. I installed [boost](https://www.archlinux.org/packages/extra/i686/boost/) and it built from the AUR just fine after that.

**Comment by jaagr** [comment]
Hi, thanks for reporting the issue.

I will try to build the project using a clean Arch install and see if the dependency list might be incomplete.

**Comment by jaagr** [comment]
Seems like I referenced the wrong boost package for arch. It should be `boost` and not `boost-libs`.

**Comment by NateBrune** [comment]
Lemonbar-git works now
