### ISSUE TITLE
lemonbuddy (or lemonbar? IDK) have integrated systray?

### ISSUE THREAD

**Issue by shackra** [jaagr/lemonbuddy#20]
I want to use another bar for the bottom part of my screen, thing is that I depend on a systray and I wouldn't like use an external application in order to have such feature. I like i3 because its integrated systray, and it is currently in use.

**Comment by jaagr** [comment]
Hi, right now there is no support for it. But I could add it.

**Comment by Bl4ckb0ne** [comment]
+1 for tray

**Comment by shackra** [comment]
@jaagr please do!

**Comment by ix** [comment]
lemonbar is just something that parses stdin and then outputs it to an x window that's docked; are you planning to just display a systray over lemonbar?

**Comment by jaagr** [comment]
No. Lemonbar will not be used anymore once the X handling has been integrated and all rendering is done internally. The tray will be done and rendered internally as well using xcb.

**Comment by ix** [comment]
hm, ok

**Comment by schubi131** [comment]
+1 for systray

**Comment by sconos** [comment]
https://github.com/emgram769/bar I've found a fork of bar which has a systray integration - maybe it'd be possible to connect it with lemonbar-sm - i gotta take a look at it next weekend.

**Comment by jaagr** [comment]
Fixed in 2.0, d359ab6
