### ISSUE TITLE
exec issue with i3-gaps

### ISSUE THREAD

**Issue by tony-liao** [jaagr/lemonbuddy#21]
I had some issues getting the bar to display on startup using i3-gaps (haven't tested it on base i3, but it's likely similar). As per instructions, I went to `~/.config/i3/config` and put
```
exec_always lemonbuddy_terminate noconfirm
exec_always lemonbuddy_wrapper <bar-name>
```
However, the bar would not appear. The problem was solved by putting a short delay between the two commands:
`exec_always sleep 0.01`

Just putting this here in case anyone had the same issue.

**Comment by jaagr** [comment]
Hi and thanks for reporting!

I will add this to the documentation.
