### ISSUE TITLE
Font not found

### ISSUE THREAD

**Issue by Bl4ckb0ne** [jaagr/lemonbuddy#22]
Hi, I have a problem with fonts with the example config file (and others that I tried).
```
$lemonbuddy_wrapper example -c ~/.config/lemonbuddy/config
Could not load font "sans:size=8"
lemonbar: invalid option -- 'o'
Could not load font "FontAwesome:size=10:weight=heavy"
lemonbar: invalid option -- 'o'
```
But I know I have font awesome installed
```
$fc-list | grep awesome
/usr/share/fonts/TTF/fontawesome-webfont.ttf: FontAwesome:style=Regular
```

Is there any more doc aboute the declaration onf the fonts in the config file? Or did I do something wrong?

Thanks.

**Comment by jaagr** [comment]
Hi and thanks for reporting!

What version of `lemonbar` are you using?

**Comment by Bl4ckb0ne** [comment]
v1.1 from [AUR](https://aur.archlinux.org/packages/lemonbar/)

**Comment by jaagr** [comment]
You would need a version patched with xft support.

I recommend the `lemonbar-sm-git` package found in the aur. That's the version I use myself.

**Comment by jaagr** [comment]
I will update the documentation to make this more clear.

**Comment by Bl4ckb0ne** [comment]
Yay it works, thanks!

BTW it works with [lemonbar-xft](https://aur.archlinux.org/packages/lemonbar-xft-git/) too

**Comment by Mardii-D-King** [comment]
What are the fonts i need to have in order for the symbols/fonts e.g. , WiFi, Ethernet, battery etc to show alongside their respected stats. Note: I already have the bar install and is seeing the stats, just not the symbols/fonts.

**Comment by jaagr** [comment]
The font used in the example config is `siji`

**Comment by Rostgnom** [comment]
I installed `siji-git` from AUR, but the icons are still not displayed at all. What am I doing wrong?

**Comment by BlackBeemo** [comment]
@Rostgnom I recently fucked up with my fonts and had the same problem
fc-list | grep siji
and replaced it with the proper name 
font-2 = Wuncon Siji:pixelsize=12;0
hope it helps you

**Comment by janhieber** [comment]
I have the same problem. Installed siji from AUR
but fc-list does not list it.
Is it because siji is not TTF/OTF?

pacman -Ql siji-git
siji-git /usr/
siji-git /usr/share/
siji-git /usr/share/fonts/
siji-git /usr/share/fonts/misc/
siji-git /usr/share/fonts/misc/siji.pcf
siji-git /usr/share/licenses/
siji-git /usr/share/licenses/siji/
siji-git /usr/share/licenses/siji/LICENSE
siji-git /usr/share/siji/
siji-git /usr/share/siji/view.sh

**Comment by jaagr** [comment]
It works fine for me. Maybe you need to rebuild the cache `fc-cache -f`
~~~
$ fc-list | grep -i Siji
~~~
> /usr/share/fonts/misc/siji.pcf: Siji:style=Regular

**Comment by janhieber** [comment]
Oh damn, I had /etc/fonts/conf.d/70-no-bitmaps.conf enabled...
Now it works. Thanks!

**Comment by Rostgnom** [comment]
@BlackBeemo
Thanks, that works :)

Now changing font size (to pixelsize=25 in the screenshot) doesn't increase the icon size, but only increases some top padding. Any solutions to that?

![image](https://cloud.githubusercontent.com/assets/7313176/22525894/74aee39a-e8c9-11e6-8b25-658431872751.png)

**Comment by jaagr** [comment]
@Rostgnom I don't think that font is scalable.

**Comment by Rostgnom** [comment]
@jaagr Oh, okay. Unfortunate font choice for the example configuration then, isn't it?

**Comment by jaagr** [comment]
Works fine for all my machines.
