### ISSUE TITLE
HIgh CPU/Memory load 

### ISSUE THREAD

**Issue by sconos** [jaagr/lemonbuddy#23]
Hi Jaagr! 

First of all, thanks for this awesome bar, i really love how simple it is!

Now to my issue: i constantly have a CPU load of about 10 percent and from time to time, lemonbuddy start to use up nearly all of my CPU and RAM.
I shamelessly stole your Lemonbuddy configurationfile so there should be no problems.

My system runs on an Arch with an i5 4210U CPU und 8GB RAM and i use bspwm :) 

Thanks in advance - I'm quite new to linux but i'll try to get more information out of my system!

Pleas find attached a sample top and htop output 
![2016-06-18-185810_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7935149/16172407/c1dfdff6-3588-11e6-9f02-4486f76d6b97.png)
![2016-06-18-190341_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7935149/16172408/c1e180a4-3588-11e6-88c7-878833b6af73.png)

**Comment by jaagr** [comment]
Hi and thank you for reporting the issue! My CPU load is usually between 0 and 1.3%. Could you try to pinpoint which module it is that causes the load by removing them from list of modules? Then I could try to debug that specific module.

**Comment by schubi131** [comment]
Hi, thanks for your reply! 
I'm gonna try to figure out which one it is, i'm gonna try to reproduce it as fast as I can - i hope i can figure something out :)

**Comment by jaagr** [comment]
The easiest thing is to just empty the three fields `modules-left`, `modules-center` and `modules-right` and then add one single module at a time to `modules-left` for example until you get to the one that causes the problem.

Appreciate the help :)

**Comment by jaagr** [comment]
My guess is that it could be the volume module, so try that one first.

**Comment by sconos** [comment]
I've tried several modules now, but was not able to reproduce the issue (i ran it only with one module at a time). 
Maybe (hopefully) it was just a onetime thing.
Cheers

**Comment by jaagr** [comment]
Ok, thanks for debugging. I've fixed quite a few bugs the last couple of days so it might have been fixed by one of those.

**Comment by sconos** [comment]
Okay perfect. Thanks a bunch!
