### ISSUE TITLE
Arch RANDR

### ISSUE THREAD

**Issue by ForgottenLegend** [jaagr/lemonbuddy#24]
I have been trying to get lemonbuddy to work, but I can't. When I try to run lemonbuddy_wrapper, it spits out: 

X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  141 (RANDR)
  Minor opcode of failed request:  42 ()
  Serial number of failed request:  10
  Current serial number in output stream:  10

I saw that there was another issue opened where they had to put their monitor in the config, however that doesn't work for me. 

Config: https://i.imgur.com/1VhuRGc.png
Xrandr: https://i.imgur.com/yPvbkZS.png

**Comment by jaagr** [comment]
Hi and thanks for reporting the issue.

What version of lemonbar are you using?

**Comment by ForgottenLegend** [comment]
I had tried lemonbar, lemonbar-git, and lemonbar-sm-git from the AUR. All the latest versions.

**Comment by jaagr** [comment]
I'm working on a patch right now that will fix the monitor handling, I will notify you once it's pushed.

**Comment by ForgottenLegend** [comment]
Thank you very much :)
