### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Bl4ckb0ne** [jaagr/lemonbuddy#25]
Hi,

I've been following your work for about a month and I faved all your posts on /r/unixporn.
Your bars are absolutely wonderful.

But all of all the screenshots you've posted on reddit, non of them have the actual lemonbuddy config file.

Is it possible to add them to the repo? Or do a lemonbuddy.github.io website, and post them as a showcase?

Thanks in advance!

**Comment by hthuong09** [comment]
Try checkout his [dotfiles repo](https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes). As he warned, the config might be too new or too old. So, be careful when put it into your config file.

**Comment by Bl4ckb0ne** [comment]
Oooh gawd, I missed that repo!
I was always in the .config/lemonbuddy folder. Thanks a lot.
