### ISSUE TITLE
bspwm-module sometimes stops reacting after hibernate

### ISSUE THREAD

**Issue by sconos** [jaagr/lemonbuddy#27]
Hi, it's me again!

I'm not sure if its a bug with lemonbuddy or lemonbar-sm, but sometimes after waking my laptop from hibernate mode, the bspwm module stops reacting - i can switch workspaces as usual but the module is not updated.

Cheers, 
sconos

P.S. i'm using lemonbuddy-git and lemonbar-sm from AUR

**Comment by jaagr** [comment]
Hi, thanks for reporting the issue! I will have a look at it.

**Comment by jaagr** [comment]
I couldn't reproduce the bug myself, but changes made in b8a1dd628e9d0993d3a890ca08347ace8bb558b1 hopefully fixes the issue. Please re-open the issue if you still have any problems with it.

**Comment by Divesh-Otwani** [comment]
Hi. I can confirm this issue is still relevant.

**Comment by jaagr** [comment]
@Divesh-Otwani what's the output of `polybar -vv`?
