### ISSUE TITLE
bspwm module socket selection for multi user

### ISSUE THREAD

**Issue by ashleymcdonald** [jaagr/lemonbuddy#29]
When more than one  user session is created the bspwm module keeps trying the first sessions socket.

ie. two user/X sessions creates two sockets
/tmp/bspwm_0_0-socket
/tmp/bspwm_1_0-socket

the 1st created session works fine but the second reports so i am assuming its trying the wrong socket.

error ** [io::socket::open] Error connecting to socket: Permission denied
error ** [io::socket::send] Error sending data: Bad file descriptor

**Comment by jaagr** [comment]
Hi, and thanks for reporting. Yeah, the socket path is currently hard coded as a cmake settings. I could make it check for an ENV variable though. That's probably better than moving the path to the config.

**Comment by jaagr** [comment]
There... Now you can control the socket path by setting the `$BSPWM_SOCKET` env variable.

**Comment by ashleymcdonald** [comment]
Sweet; thanks alot
