### ISSUE TITLE
Run modules sandboxed

### ISSUE THREAD

**Issue by patrick96** [jaagr/lemonbuddy#30]
Every module should be run so that, even if it fails, all other modules are still displayed.
A try catch block should probably be able to catch almost every error thrown. But maybe there will be some uncathable exceptions that can get through (if those even exist in cpp)

For one this is very useful for testing your bar
But also you do not have to check if your custom modules fail. (For example I think `xtitle -s` crashes the current bar cycle when there has never been a window open)

**Comment by ashleymcdonald** [comment]
+1

Would be good on one of my machines where the power adapter is not there
unless it's plugged in at boot. But it's an issue I need to research when I
have time :p. As it crashes the battery module.

For xtitle just wrap it with an echo at the start
On Sun., 10 Jul. 2016 at 6:02 am, Patrick Ziegler <notifications@github.com>
wrote:

> Every module should be run so that, even if it fails, all other modules
> are still displayed.
> A try catch block should probably be able to catch almost every error
> thrown. But maybe there will be some uncathable exceptions that can get
> through (if those even exist in cpp)
>
> For one this is very useful for testing your bar
> But also you do not have to check if your custom modules fail. (For
> example I think xtitle -s crashes the current bar cycle when there has
> never been a window open)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaagr/lemonbuddy/issues/30>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHHkMvvSHKfq9cX_6U1yc8mZGQICrvVQks5qT_5egaJpZM4JIsPS>
> .
>
-- 
Cheers,

Ash
--
*Ashley McDonald*
Founder, Internet Guru
t: +613 9005 3907
m: +614 3311 4895
e: ashley@mcdonald.am
w: http://ashley.mcdonald.am/
<https://twitter.com/MrAshMcDonald?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 MrAshMcDonald
<http://www.opensource.am/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Opensource.am
<http://www.closedsource.am/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Closedsource.am
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

Disclaimer: This email is intended for the use of the individual
addressee(s) named above and may contain information that is confidential,
privileged or unsuitable for overly sensitive persons with low self-esteem,
no sense of humour or irrational religious beliefs. If you are not the
intended recipient, any dissemination, distribution or copying of this
email is not authorised (either explicitly or implicitly) and constitutes
an irritating social faux pas. Unless the word absquatulation has been used
in its correct context somewhere other than in this warning, it does not
have any legal or grammatical use and may be ignored.

By sending an email to ANY of my addresses you are agreeing that:
- I am by definition, "the intended recipient"
- All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to.
- I may take the contents as representing the views of your company.
- This overrides any disclaimer or statement of confidentiality that may be
included on your message.

**Comment by jaagr** [comment]
I agree. A log message about it failing should be sufficient. I'm on vacation at the moment but I'll have a look at it once I get back.

**Comment by jaagr** [comment]
Fixed in 2.0, 89d6455
