### ISSUE TITLE
Cannot `make install`

### ISSUE THREAD

**Issue by Marcel-Robitaille** [jaagr/lemonbuddy#31]
When I run `cmake ..`, everything is perfect. Then I run `sudo make install and I get this:
```
~/lemonbuddy/build on 3ad583b 
➔ sudo make install
[  2%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/marcel/lemonbuddy/lib/xpp/generators/cpp_client.py", line 3162, in <module>
    from xcbgen.state import Module
ImportError: No module named xcbgen.state
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

I have to recompile because the package in the aur does not seem to support i3 (am I correct?). Anyway it doesn't work.

`uname -a`:
```
Linux Hermes 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```

**Comment by ashleymcdonald** [comment]
the package(s) in the aur support i3; you need the dependencies installed.

**Comment by Marcel-Robitaille** [comment]
@ashleymcdonald I have jsoncpp libsigc++ and the i3 example still does not work.

**Comment by ashleymcdonald** [comment]
when compiling from one of the aur versions (that install fine i assume) does it say yes to i3 support early in the process ? 
I'm personally a bspwm user myself so i have not used the i3 modules but support for i3 is definitely in the aur versions. 
I'm guessing you will have to wait for @jaagr to chime in. 
Good luck

**Comment by ashleymcdonald** [comment]
ps. your original error looks like you dont have libxcb

**Comment by jaagr** [comment]
Hi @Marcel-Robitaille 

Sorry for the late respons, but I've been on vacation the past few weeks. As @ashleymcdonald mentioned it's an xcb issue. I'm not sure what package manager you are using but you will need to install the equivilant of the `libxcb` pacman package or apt-get's `libxcb1-dev`.

**Comment by Marcel-Robitaille** [comment]
I no longer need to compile my own version. The aur package has support for i3. The issue must lie elsewhere.

I am still getting the issue when trying to `sudo make install` even with pacman's `libxcb` installed (version 1.12-1).

**Comment by jaagr** [comment]
What distro are you using? Try installing `xcb-proto`.

**Comment by Marcel-Robitaille** [comment]
`xcb-proto` is installed and is version 1.12-2.

**Comment by jaagr** [comment]
Could you post the output of this command:

    $ find /usr/lib -name xcbgen -type d

**Comment by Marcel-Robitaille** [comment]
Sorry, I was away from this computer for a few days. Anyway:
```
~ 
➔ find /usr/lib -name xcbgen -type d
/usr/lib/python3.5/site-packages/xcbgen
```

**Comment by jaagr** [comment]
Ok, then I know what's causing the issue. I'll patch the build routine.

**Comment by patrick96** [comment]
Just for future reference:
The `lib/xpp/CMakeLists.txt` searches in `/usr/lib/python2.7/site-packages` whereas (on arch at least) the relevant files are in the `/usr/lib/python3.5/site-packages` folder
The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lemonbuddy-git) for lemonbuddy in the AUR actually corrects the paths using
```
sed 's/python2.7/python3.5/g' -i lib/xpp/CMakeLists.txt
```
So if the AUR package builds for you, then you can just use the build instructions from there and it should work for you.
