### ISSUE TITLE
Display on all Monitors

### ISSUE THREAD

**Issue by patrick96** [jaagr/lemonbuddy#32]
I would like to see the ability to display the bar on all the monitors present.
And maybe also a way to specify multiple monitors where the bar should be displayed (if the monitor exists)

I am using a dual monitor setup on my desktop and want to share my configs with my laptop that has other names for its monitor (and also only one). Right now I would have to define three bars that only differ in their monitor value, per bar I want to display on each monitor.

**Comment by patrick96** [comment]
I have not dug into the code that much but I think this would be possible by returning a string array in `get_exec_line` and by allowing multiple monitors to be specified in the `monitor` option.
Also if the monitor value is empty it could be set to all connected monitors by default

**Comment by jaagr** [comment]
Hi. This will be solved once I publish the new rendering code that replaces `lemonbar`, which has been post-poned since I've been working on the systray functionality.. I will implement your idea about multiple monitor names.
