### ISSUE TITLE
ability to continue if (network) device is not found

### ISSUE THREAD

**Issue by AtzeDeVries** [jaagr/lemonbuddy#35]
Hi,

I have a laptop without an ethernet interface, but on my desktop there is a usb3 interface i use. I also would like to show the status of my vpn setup.

For example, my vpn (tunnel) interface is on /dev/tun0 . If i use this config:
```
[module/network]
type = internal/network
interface = tun0
```
and the vpn is not set, lemmonbuddy crashes. 

It would be nice to have a status `not available` of some kind of `if` statement

**Comment by jaagr** [comment]
Hi, and thanks for reporting. Plans are to make the modules run sandboxed (see #30) which would solve this issue. Until then I'd recommend having 2 bar configs with different network modules.
