### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by ib250** [jaagr/lemonbuddy#36]
I don't tweak it much, but I've been using it for a while now and it's a fantastic tool. Typically when I change xresources colors or connect a monitor I'd like lemonbuddy to comply. This can be done without changing the config if I can access environment variables.

**Comment by patrick96** [comment]
I second that. You already do variable expanstion to access properties of other config options in the lemonbuddy config, so it should be possible to also incluce environment variables if they exist

**Comment by jaagr** [comment]
Yeah, this only requires a minor change to the config code so I'll push a commit with it in a few hours.

**Comment by jaagr** [comment]
With e94bd6a271 you can reference variables using `${env:VAR_NAME}`

**Comment by ib250** [comment]
Man! that was quick!
