### ISSUE TITLE
Help a noob trying to use unicode in his bar

### ISSUE THREAD

**Issue by malynome** [jaagr/lemonbuddy#45]
Hi, I'm trying to display some of the icons from FontAwesome, but I have trouble copy&pasting them, so I tried to use the unicode instead. I can't get the icon to show up, only the code, I've tried fx. \f026, \uf026 etc.
Is there a way to do this, or can you point me in the right direction?
Thanks in advance,
Martin

**Comment by patrick96** [comment]
Adding the hex codes will not work.
If you have problems copying icons but know the hex code, you can run the following:
```
echo -ne "\uf026" | xclip -selection clipboard
```
This will copy the symbol to your clipboard and you can paste it into the lemonbuddy config (although you probably won't see it in the editor, only on the bar)
If the copying doesn't work, you may need to replace `clipboard` with `primary` or `secondary`

**Comment by malynome** [comment]
Okay, thanks for the quick reply!

**Comment by patrick96** [comment]
Tell me if it works for you. Non copyable characters are a real pain

**Comment by malynome** [comment]
Hey man, it worked! thanks alot.

**Comment by patrick96** [comment]
In cases like this what you could do is have a config file with your text symbols that you source before you (re)start the bar that looks something like this
```
export VOL1="$(echo -e "\uf026")"
```
And in the lemonbuddy config you can the reference that icon like so
```
ramp-volume-0 = ${env:VOL1}
```

**Comment by fredcox** [comment]
Where are i can copy font symbol for siji for example?
