### ISSUE TITLE
Support for WM_URGENT hinting.

### ISSUE THREAD

**Issue by Toqozz** [jaagr/lemonbuddy#46]
I have pidgin with some plugins that send notifications through libnotify and also raise the wm_urgent flag.  

In bspwm you can set WM_URGENT_BORDER_COLOR and the default lemonbar config for bspwm highlights urgent desktops in a color defined (in panel_colors).

Right now when a desktop is marked as urgent lemonbuddy changes whatever characters you had set (in lemonbuddy config) to the desktop names (in bspwmrc).

I don't think I'm explaining it very well but hopefully this makes it more obvious:

lemonbuddyconf:
`label-occupied = `

bspwmrc:
`bspc monitor '^1' -d misc chat view web`

Result on urgent:
![Issue descriptor](http://i.imgur.com/xY1RSoX.png)

**Comment by patrick96** [comment]
OK, I think I understand your problem now. So whenever a workspace (desktop whatever) is marked urgent, lemonbuddy does not show the label you defined in the lemonbuddy config but rather the name you set for the desktop in your `bspwmrc`, right?
Alright first of all, what you posted from you lemonbuddy config is `label-occupied`, what you want to set is `label-urgent`. If it is not set, the default is `%icon% %name%` where `%icon%` is whatever you set in `workspace_icon-X` with a fallback to `workspace_icon-default` and `%name%` is simply the name of the desktop. 
If you think this is not the problem, please post your entire lemonbuddy config and I will investigate further.

**Comment by Toqozz** [comment]
I did not know that was an option, thank you.

On 20 Aug 2016, at 17:36, Patrick Ziegler <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I think I understand your problem now. So whenever a workspace (desktop whatever) is marked urgent, lemonbuddy does not show the label you defined in the lemonbuddy config but rather the name you set for the desktop in your bspwmrc, right?
Alright first of all, what you posted from you lemonbuddy config is label-occupied, what you want to set is label-urgent. If it is not set, the default is %icon% %name% where %icon% is whatever you set in workspace_icon-X with a fallback to workspace_icon-default and %name% is simply the name of the desktop.
If you think this is not the problem, please post your entire lemonbuddy config and I will investigate further.

-
