### ISSUE TITLE
Failed to open "Master" mixer => [Alsa] Cannot find simple element

### ISSUE THREAD

**Issue by jieverson** [jaagr/lemonbuddy#48]
I'm getting this error trying to run lemonbuddy. I had to remove the volume module to get it working.
I'm current using sxhkd shortcuts to change my alsa volumes, but I would like to see the volume level at the bar.

**Comment by patrick96** [comment]
Could you please post the lemonbuddy config you were using when it crashed
Are you running lemonbuddy as root?
Also could you give me the result of the following commands:
`aplay -l` - This gives me a list of all of your soundcards
`amixer -D default scontrols` - This gives me a list of available mixers
What command do you use in sxhkd to change the volume?

**Comment by jieverson** [comment]
I'm not at home right now, but I was using the default config for bspwm, and wasn't running it as root. At night I can give more info. Also, network module was not working. I'm using the AUR package, and seens it is not compiled to network module. I will try the .git package from AUR at night.

**Comment by patrick96** [comment]
The AUR packages should both have network support, if you have [wireless_tools](https://www.archlinux.org/packages/core/i686/wireless_tools/) installed.
It is probably just that the interface in the config is wrong. But I can tell you more when I see the configs.

Also for the network module, can you give me the output of `ip link`?

**Comment by jieverson** [comment]
This are my `aplay -l` and `amixer -D default scontrols`:
![2016-08-25-190234_623x375_scrot](https://cloud.githubusercontent.com/assets/1031323/17987462/7f9d0706-6af6-11e6-9f5d-ef4874d1d779.png)

For changing volume I use this at my sxhkd:
```
XF86AudioRaiseVolume
	sh -c "pactl set-sink-mute 1 false ; pactl set-sink-volume 1 +5%"

XF86AudioLowerVolume
	sh -c "pactl set-sink-mute 1 false ; pactl set-sink-volume 1 -5%"

XF86AudioMute
	pactl set-sink-mute 1 toggle
```

My `ip link`:
![2016-08-25-190447_956x146_scrot](https://cloud.githubusercontent.com/assets/1031323/17987543/d5f88fee-6af6-11e6-8f48-6a53127ce1d2.png)

My config:
```
[settings]
; Limit the amount of events sent to lemonbar within a set timeframe:
; - "Allow <throttle_limit> updates within <throttle_ms> of time"
; Default values:
;throttle_limit = 5
;throttle_ms = 50

[bar/example]
;monitor = eDP1
top = true
dock = true

width = 100%
height = 20

;offset_x = 0
;offset_y = 0

background = #333232
foreground = #a7a5a5
;linecolor = #ff0000

spacing = 1
lineheight = 1

separator = |

;locale = en_US.UTF-8

padding_left = 1
padding_right = 1
module_margin_left = 0
module_margin_right = 0

font-0 = sans:size=8;0
font-1 = FontAwesome:size=10:weight=heavy;0

modules-left = label
modules-center = bspwm
modules-right = volume cpu ram clock

[module/label]
type = custom/text
content = Lemonbuddy example
content-background = #af2031
content-underline = #cf4253
content-overline = #cf4253
content-padding = 2

[module/cpu]
type = internal/cpu
label = CPU: %percentage%
;format-background = #c42
;format-underline = #f75
;format-overline = #f75
format-padding = 2

[module/ram]
type = internal/memory
label = RAM: %percentage_used%
;format-background = #42c
;format-underline = #75f
;format-overline = #75f
format-padding = 2

[module/clock]
type = internal/date
date = %Y-%m-%d %H:%M
;format-background = #493
;format-underline = #7a6
;format-overline = #7a6
format-padding = 2

[module/volume]
type = internal/volume
;speaker_mixer = Speaker
;headphone_mixer = Headphone
;headphone_control_numid = 9

format-volume-background = #933484
format-volume-underline = #9d6294
format-volume-overline = #9d6294
format-volume-padding = 2
format-muted-background = #933484
format-muted-underline = #9d6294
format-muted-overline = #9d6294
format-muted-padding = 2

label-volume = Volume: %percentage%
label-muted = Sound is muted

[module/bspwm]
type = internal/bspwm
label-active = 
label-active-padding = 1
label-active-foreground = #C3C322
label-occupied = 
label-occupied-padding = 1
label-occupied-foreground = #AD2BEE
label-empty = 
label-empty-padding = 1
label-empty-foreground = #AD2BEE

[module/wireless]
type = internal/network
interface = wlan1

[module/battery]
type = internal/battery
; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC
; full_at = 99
poll_interval = 30
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-full =  %percentage%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width = 10

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate_ms = 750

; vim:ft=dosini
```

I installed `wireless_tools` after getting lemonbuddy from AUR.

**Comment by patrick96** [comment]
As I suspected. You need non default values for for your volume and network modules. Your wireless interface is called `wlp3s0` and not `wlan1`

As for the volume, you should add `master_mixer = IEC958` to the module. Btw on the [README](https://github.com/jaagr/lemonbuddy#module-internalvolume) it tells you how to get your mixer names.

**Comment by jieverson** [comment]
I have cleaned my config and set default values.

When I try to use a volume module, the bar does not render anything, and I get this:
![2016-08-25-205258_958x45_scrot](https://cloud.githubusercontent.com/assets/1031323/17989740/f8ff54aa-6b05-11e6-915d-2c8f07946f60.png)

My volume module:
```
[module/volume]
type = internal/volume
master_mixer = IEC958
```

When I try to use a network module, I get this:
![2016-08-25-205512_945x30_scrot](https://cloud.githubusercontent.com/assets/1031323/17989781/3ca010f0-6b06-11e6-8da1-a9e074d60018.png)
(and yes, I have `wireless_tools` installed)

My volume network module:
```
[module/wireless]
type = internal/network
interface = wlp3s0
```

**Comment by patrick96** [comment]
For the network module, you need to rebuild lemonbuddy from the AUR, modules are enabled at compile time, it's of no use installing a dependency later.
As for the volume module, I'm not really sure what's going on. Try putting the value of `master_mixer` in quotes: `master_mixer = "IEC958"`. Also always make sure the error really comes from that module by removing all the others.

**Comment by jieverson** [comment]
I had rebuild the AUR package, and now things are working (except for the volume):
![16-08-25-21 53 55](https://cloud.githubusercontent.com/assets/1031323/17990707/75e26112-6b0e-11e6-83e4-2c9916cdfd67.png)
> I have even put a language script at the bar.

Still have no idea why bar stops working when I put volume at the bar. =s (have tried the quotes)
```
[module/volume]
type = internal/volume
master_mixer = "IEC958"
speaker_mixer = "IEC958"
```

**Comment by patrick96** [comment]
The colors can be specified in the `#aarrggbb` format. If you don't have a compositor running, the alpha channel is ignored.

Alright, can I see your new volume module.
Also what is the output of `amixer scontrols` now?
Finally I need a screenshot of what you see when you open up `alsamixer`

**Comment by jieverson** [comment]
My module:
```
[module/volume]
type = internal/volume
speaker_mixer = Speaker
headphone_mixer = Headphone
headphone_control_numid = 23
format-volume =    <label-volume>
label-muted =  muted
```
![2016-08-26-135836_380x262_scrot](https://cloud.githubusercontent.com/assets/1031323/18013648/6fd98f0c-6b95-11e6-9ac0-1ff6c8a4ed90.png)

![2016-08-26-135850_959x844_scrot](https://cloud.githubusercontent.com/assets/1031323/18013661/81f0992e-6b95-11e6-8847-99c3f1bc2c7e.png)

**Comment by patrick96** [comment]
I think,  I got it:
Remove `speaker_mixer` and `headphone_mixer` and just set `master_mixer =
Master`

Jiéverson <notifications@github.com> schrieb am Fr., 26. Aug. 2016, 19:01:

**Comment by jaagr** [comment]
Closing for now.. re-open if needed
