### ISSUE TITLE
High xorg cpu usage

### ISSUE THREAD

**Issue by pepton-1** [jaagr/lemonbuddy#50]
Hi. I'm having unusually high xorg cpu usage when running lemonbuddy with default config:
```
throttle_limit = 5
throttle_ms = 50
```
It goes from 3.3% to 10%, with about 7% on average. Is that something normal?

**Comment by patrick96** [comment]
I just checked on my side and it seems this is the case. But this would be more of an issue with lemonbar and not with lemonbuddy. But you can probably decrease the CPU usage by tweaking the throttle values, this will make lemonbuddy send less updates to lemonbar which in turn decreases the number of times the bar is updated. However, the bar may noticeably lag behind if you allow to few updates in a given timeframe

**Comment by pepton-1** [comment]
Thanks, will do that.

**Comment by jaagr** [comment]
Closing for now.. re-open if needed
