### ISSUE TITLE
Help using multiple fonts

### ISSUE THREAD

**Issue by absolutejam** [jaagr/lemonbuddy#53]
Hey,

I've been trying to get some fontawesome icons working in my LemonBar, but I'm at a loss as how to define them.

I've applied some of the extended configurations from the README (with ramp value), but I'm not sure how I can have multiple fonts. I currently have the following defined:
```
 44 font-0 = terminus:size=9
 45 font-1 = Unifont:size=10:weight=heavy;0
```
and the `font-0` is being applied to my main text, `font-1` is being applied to the CPU loading bar. But this leaves my icons not wanting to load, so if I wanted to define another font (just for the icons on each section), how would I do so?

Sorry to be a pain!

**Comment by ashleymcdonald** [comment]
How to define fonts (more than 2)

    ; Fonts are defined using: <FontName>;<Offset>
    font-0 = NotoSans-Regular:size=8;0
    font-1 = MaterialIcons:size=10;0
    font-2 = Termsynu:size=8;-1
    font-3 = FontAwesome:size=10;0

and an example applying that font to a progress bar fill

    bar-progress-fill = ─
    bar-progress-fill-foreground = #bb
    bar-progress-fill-font = 3

**Comment by ashleymcdonald** [comment]
some more examples from @jaagr's [dot files](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/wasp/lemonbuddy)

https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/wasp/lemonbuddy

**Comment by patrick96** [comment]
The way fonts are used is, for every character lemonbar wants to render, it goes through all the defined fonts in order (starting at 0) searching for the character until it finds it.
Also another note, there is a max amount of fonts you can define, for the [default bar](https://github.com/LemonBoy/bar) this maximum is 5 but for the one that is [recommended in the README](https://github.com/osense/bar) the maximum is 8.

**Comment by jaagr** [comment]
Closing this for now.. re-open if needed
