### ISSUE TITLE
"Invalid geometry specified" if locale is set

### ISSUE THREAD

**Issue by PhilippSchaffrath** [jaagr/lemonbuddy#56]
The lemonbar does not render and prints the error "Invalid geometry specified" once a locale has been defined. It seems like it doesn't matter what locale you set. The error will be printed out as soon as a locale is present in the configuration.

```
[bar/something]
locale = de_DE.UTF-8
```

**Comment by PhilippSchaffrath** [comment]
I don't know why, but using `setlocale` instead of `locale::global` fixes the problem.

**Comment by jaagr** [comment]
`setlocale` only affects C locale.. b940d64 should fix the problem though
