### ISSUE TITLE
Lemonbuddy does not respond after resuming from hibernation

### ISSUE THREAD

**Issue by NateBrune** [jaagr/lemonbuddy#6]
At the moment I can't get a debug log of any sorts to you, but I will try tomorrow. But yeah essentially after I resume from suspend, lemonbar doesn't update anymore. Whats worse is that it actually takes down a cpu core with it (some sort of loop maybe is demanding 100% of the core it was running on after resuming). It essentially freezes. 
To be exact the issue I am observing is that once I type killall lemonbuddy and killall lemonbar (because they are frozen after resume) the lemonbuddy_wrapper.sh script continues to run using 100% of the cpu.

**Comment by jaagr** [comment]
How do you start the bar? In your wm's init script?

I updated the README a few hours ago, with some details on killing previous bars. It might fix the looping issue:
https://github.com/jaagr/lemonbuddy#launching-the-bar-in-your-wms-bootstrap-routine

I have no idea why it freezes after resuming though. I will look into it.

**Comment by jaagr** [comment]
I can't reproduce the problem with my settings.

Could you post your config and details about your system.

Also make sure you update to the latest version. Use the new `lemonbuddy-git` package in the AUR.

**Comment by NateBrune** [comment]
Yeah... I am sorry. I originally believed that this was cause by hibernation, but I need to do a better job tracking down the bug. They symptoms are the same, but I am going to look for the cause.

**Comment by jaagr** [comment]
Did you try the [git package](https://aur.archlinux.org/packages/lemonbuddy-git/)?
