### ISSUE TITLE
Battery module fails to update

### ISSUE THREAD

**Issue by birjolaxew** [jaagr/lemonbuddy#62]
My battery status is read correctly when the bar is launched, but then never updates; I would assume it has to do with [`BatteryModule::subthread_route`](https://github.com/jaagr/lemonbuddy/blob/master/src/modules/battery.cpp#L100) not respecting the `battery` config (I have it set to `BAT1`, not `BAT0`).

[Related config.](http://pastebin.com/QGyGhmeg)

OS: Arch
WM: bspwm

**Comment by jaagr** [comment]
Thanks for reporting. I've replaced the hard coded path and pushed a fixed version.
