### ISSUE TITLE
low battery option

### ISSUE THREAD

**Issue by Piczel** [jaagr/lemonbuddy#63]
Hi bro,

i was contempling my bar, but i saw there is no "low" option for the battery, there is a full one, as "full_at", or "format-full-background" for example, but neither "low_at" nor "format-low-*".

Is that me that is a dumb idiot which can't read a wiki ? Or  is that lemonbuddy that doesn't support that ? (in this case, is that planned ?)

thx, sorry for my franglish :+1:

**Comment by jaagr** [comment]
Hi

There's no config option for it today. I usually use `ramp-capacity-N` to display the icon in red when it gets low for example.

**Comment by Piczel** [comment]
Oh good idea, i didn't think about that, thx !

**Comment by jediofthecode** [comment]
@jaagr do you have an example of this ?

**Comment by jaagr** [comment]
Something like this:

~~~ini
[module/battery]
type = internal/battery
full_at = 98

format-discharging = <ramp-capacity> <label-discharging>

ramp-capacity-0 = 
ramp-capacity-0-foreground = #de0037
ramp-capacity-1 = 
ramp-capacity-2 = 
~~~

**Comment by jaagr** [comment]
Closing this issue since the given solution should be enough for customizing the output when the battery level is low.

**Comment by p3lim** [comment]
Assuming ramps are dynamic, if I created 6 instances (ramp-capacity0-5) it would split them at every 16.6~%, correct?

Relevancy of that to this issue is adding more ramps to lower the "low battery" threshold with the forground color on the lowest increment (0).

**Comment by jaagr** [comment]
Yeah, that's correct.
