### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by Eizen** [jaagr/lemonbuddy#64]
Cmake log: http://hastebin.com/afoxaqoyaq.hs
Make install log: http://hastebin.com/otizehixog.md

Hi, trying to build source code on Solus. Had installed all the dependencies (even jsoncpp and jsoncpp-devel which the error seems related to). I'm using i3 and cmake detects it and run just fine.

**Comment by patrick96** [comment]
You're version of jsoncpp is ancient, try to use the newest one from [here](https://github.com/open-source-parsers/jsoncpp), you might need to uninstall the one you already have

**Comment by Eizen** [comment]
@patrick96 Updating jsoncpp did the trick, thanks.
