### ISSUE TITLE
Media player script not found (Spotify)

### ISSUE THREAD

**Issue by jlobos** [jaagr/lemonbuddy#65]
Hi, i'm trying to do this:

```
[module/spotify]
type = custom/script
exec = ~/.dotfiles/config/i3/scripts/mediaplayer
tail = true
```

the mediaplayer script is [mediaplayer](https://github.com/jlobos/dotfiles/blob/master/config/i3/scripts/mediaplayer) but it does not work, i run in terminal and found: 

```sh
$ /usr/bin/env sh -c ~/.dotfiles/config/i3/scripts/mediaplayer
```

**Comment by patrick96** [comment]
Do you get any errors when starting the bar?
Is the whole bar blank or is the module just missing?

**Comment by jlobos** [comment]
@patrick96 bar in blank, i no open Spotify and test and show: 

```
Connection to player failed: No players found
```

But open Spotify the bar is blank. 😢
Before i using `i3blocks` and this config the script work:

```
[mediaplayer]
command=perl ~/.dotfiles/config/i3/scripts/mediaplayer
instance=spotify
interval=5
signal=10
```

**Comment by patrick96** [comment]
This doesn't seem to be an issue with lemonbuddy.
What happens if you call 
```/usr/bin/env sh -c ~/.dotfiles/config/i3/scripts/mediaplayer```
from the command line?

Also try this:
```dosini
exec = env BLOCK_INSTANCE=spotify ~/.dotfiles/config/i3/scripts/mediaplayer
```

**Comment by jlobos** [comment]
![2016-09-16-17 11 09](https://cloud.githubusercontent.com/assets/11975868/18599963/6f7b106a-7c31-11e6-8035-fb2d8d7b198f.png)


Output:

```
$ /usr/bin/env sh -c ~/.dotfiles/config/i3/scripts/mediaplayer
The Strumbellas - Spirits - Sondr Remix 
```

`exec = env BLOCK_INSTANCE=spotify ~/.dotfiles/config/i3/scripts/mediaplayer` not found :(

**Comment by jlobos** [comment]
I give up :(

**Comment by jaagr** [comment]
I'll have a look at the script, but I can see that the script output in your terminal doesn't end with a new line `\n` which would cause a problem.

**Comment by jaagr** [comment]
This would work. Tailing won't work since there's no continous output from the script.

~~~ini
[module/spotify]                                                                                                               
type = custom/script
exec = BLOCK_INSTANCE=spotify ~/sandbox/mediaplayer.pl | xargs echo
interval = 5
~~~

**Comment by jlobos** [comment]
@jaagr Awesome, thank!!
