### ISSUE TITLE
Error at cmake ..

### ISSUE THREAD

**Issue by veggiedefender** [jaagr/lemonbuddy#66]
Installing from the AUR (both the git and non-git version) as well as following your directions on building from source result in this:

    cmake ..
    -- The C compiler identification is GNU 6.2.1
    -- The CXX compiler identification is GNU 6.2.1
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- No build type specified; using Release
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
    -- Boost version: 1.61.0
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Checking for module 'sigc++-2.0'
    --   No package 'sigc++-2.0' found
    CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
      A required package was not found
    Call Stack (most recent call first):
      /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
      lib/i3ipcpp/CMakeLists.txt:13 (pkg_check_modules)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/jesse/Desktop/lemonbuddy/build/CMakeFiles/CMakeOutput.log".
    See also "/home/jesse/Desktop/lemonbuddy/build/CMakeFiles/CMakeError.log".
    
Here's the [CMakeOutput.log](http://hastebin.com/sabohotejo.sql) and [CMakeError.log](http://hastebin.com/omuxewahar.bash)

**Comment by patrick96** [comment]
You're missing the [libsigc++](https://www.archlinux.org/packages/extra/x86_64/libsigc++/) package. This is a dependency, if you have i3 installed.

@jaagr Maybe the cmake script could just disable the i3 module if any of it's dependencies aren't found instead of just failing.

**Comment by veggiedefender** [comment]
Thank you so much! It works now.

**Comment by jaagr** [comment]
@patrick96 That's how it worked before but I reverted back to fail fast since there would be more questions about why the i3 module doesn't work. At least now it's clear that a dependency is missing. Should maybe add a note to the README on how to disable the module using `cmake -DENABLE_I3:BOOL=OFF` though.
