### ISSUE TITLE
Issue with outputs

### ISSUE THREAD

**Issue by WhatsCS** [jaagr/lemonbuddy#69]
I'm currently using Antergos with bspwm and am running into an issue. Every time I try and run `lemonbuddy_wrapper test`  I get: `Selected output unavailable`. I've tried using bspwm's bar config that comes standard and it works without any issues. There's nothing in any log files that I can see, and setting the logging to debug doesn't provide anything either.

**Comment by patrick96** [comment]
I am not at my computer right now so I can't test this. But I think this
means you set the wrong monitor in the lemonbuddy configs. Run `xrandr` to
get the names of your monitors and use those names in the config. There
should be more info about that in the readme

WhatsCS <notifications@github.com> schrieb am So., 9. Okt. 2016, 21:25:

**Comment by WhatsCS** [comment]
I've used both monitor names and I have also use no monitor. For some reason lemonbuddy is seeing it as, what I'm assuming is, in use.

**Comment by patrick96** [comment]
What fork of lemonbar are you using? Try using [this one](https://github.com/osense/bar) and see if anything changes.

**Comment by WhatsCS** [comment]
I'm using the fork jaagr has in his readme, which is that one. It fixed my issue with fonts and that's about it.

**Comment by jaagr** [comment]
@WhatsCS, could you show us the config you're using and the output of `xrandr -q`

**Comment by WhatsCS** [comment]
```
$ xrandr -q
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
VGA-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1080     59.96*+  60.00  
   2560x1600     59.99    59.97  
   1920x1440     60.00  
   1856x1392     60.00  
   1792x1344     60.00  
   2048x1152     60.00  
   1920x1200     59.88    59.95  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1400x1050     59.98    59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.89    59.90  
   1280x960      60.00  
   1366x768      59.79    60.00  
   1360x768      60.02  
   1280x800      59.81    59.91  
   1280x768      59.87    59.99  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
VGA-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1080     59.96*+  60.00  
   2560x1600     59.99    59.97  
   1920x1440     60.00  
   1856x1392     60.00  
   1792x1344     60.00  
   2048x1152     60.00  
   1920x1200     59.88    59.95  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1400x1050     59.98    59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.89    59.90  
   1280x960      60.00  
   1366x768      59.79    60.00  
   1360x768      60.02  
   1280x800      59.81    59.91  
   1280x768      59.87    59.99  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94
```
```
$ cat config
[settings]
; Limit the amount of events sent to lemonbar within a set timeframe:
; - "Allow <throttle_limit> updates within <throttle_ms> of time"
; Default values:
;throttle_limit = 5
;throttle_ms = 50

[bar/test]
monitor = VGA-1
bottom = false
dock = false

width = 100%
height = 15

;offset_x = 0
;offset_y = 0

background = #00ffffff
foreground = #fff
;linecolor = #ff0000

spacing = 1
lineheight = 1

;separator = |

locale = en_US.UTF-8

padding_left = 1
padding_right = 1
module_margin_left = 0
module_margin_right = 0

font-0 = Source Code Pro for Powerline:style=Regular:size=8;0
font-1 = FontAwesome:size=10:weight=heavy;0

modules-left = xtitle
modules-center = bspwm
modules-right = volume cpu ram clock

[module/xtitle]
type = custom/script
exec = xtitle -s
tail = true

[module/cpu]
type = internal/cpu
label = CPU: %percentage%
format-background = #c42
format-underline = #f75
format-overline = #f75
format-padding = 2

[module/ram]
type = internal/memory
label = RAM: %percentage_used%
format-background = #42c
format-underline = #75f
format-overline = #75f
format-padding = 2

[module/clock]
type = internal/date
date = %Y-%m-%d %H:%M
format-background = #493
format-underline = #7a6
format-overline = #7a6
format-padding = 2

[module/volume]
type = internal/volume
;speaker_mixer = Speaker
;headphone_mixer = Headphone
;headphone_control_numid = 9

format-volume-background = #933484
format-volume-underline = #9d6294
format-volume-overline = #9d6294
format-volume-padding = 2
format-muted-background = #933484
format-muted-underline = #9d6294
format-muted-overline = #9d6294
format-muted-padding = 2

label-volume = Volume: %percentage%
label-muted = Sound is muted

[module/bspwm]
type = internal/bspwm
label-active = 
label-active-padding = 1
label-occupied = 
label-occupied-padding = 1
label-empty = 
label-empty-padding = 1

; vim:ft=dosini
```

**Comment by jaagr** [comment]
What happens if you remove the `monitor` setting?

**Comment by WhatsCS** [comment]
Same issue. I don't really understand how lemonbuddy works internally so I can't come up with a clever idea. Could it be a pipe issue?

**Comment by jaagr** [comment]
I'm not sure. I have rewritten the application and I'm doing the final touch-ups before releasing 2.0 so I won't do any changes for the current release. If you'd like you could try building the `2.0-beta` branch.

**Comment by WhatsCS** [comment]
Sounds like a plan! I'll try it out and see if it'll work.

**Comment by jaagr** [comment]
Just remember that it's not a released version so stuff might not work... also, the lemonbuddy_wrapper script is no longer used, so just run `lemonbuddy bar_name -c ~/path/to/config` (no lemonbar stuff, since it's not used anymore)

**Comment by WhatsCS** [comment]
I can't compile, undefined reference to pthread_create.

**Comment by jaagr** [comment]
I've only built it using clang so far, so if you have it installed you should run this in the build folder:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..`

**Comment by WhatsCS** [comment]
Sorry for the late response, I'm unable to build with make after the new push. I decided to pull from the AUR since that was updated to the newest version. That worked without issues. Thanks for the help!

**Comment by jaagr** [comment]
Awesome.. well the aur package gets built like if you'd do it manually so should work.. glad it's sorted at least :)
