### ISSUE TITLE
Battery module updating/refreshing very inconsistantly

### ISSUE THREAD

**Issue by ChristopherWMartin** [jaagr/lemonbuddy#7]
Using bspwm on Arch Linux, the battery indicator updates at a seemingly random interval, usually not for hours, while everything else that I'm using (workspace indicator, backlight, clock) all function perfectly.

**Comment by jaagr** [comment]
Hi and thanks for reporting. Are you using the latest version? I committed some changes to it a few days ago that fixed it with my testing at least.

**Comment by ChristopherWMartin** [comment]
I should be using the most recent version. I installed the AUR git package yesterday. I wish I could give you more information to replicate this issue -- 'cat /sys/class/power_supply/BAT0/current' returns expected results as well as Yabar and Tint2.

**Comment by jaagr** [comment]
The code is using `/sys/class/power_supply/%battery%/capacity` to get the current percentage.

Could you post the battery section of your configuration.

**Comment by jaagr** [comment]
The problem is either caused by the inotify event's not firing or the charging animation thread not getting the correct values. I will pull up my arch machine and do some more testing to see if I can find anything.

Does the problem occur when discharging, charging or both?

**Comment by jaagr** [comment]
What version does pacman report?

``` sh
$ pacman -Q lemonbuddy-git
````

**Comment by jaagr** [comment]
I can confirm the bug. I just tried the latest version on my Arch machine. Will fix it and notify you when it's done.

**Comment by ChristopherWMartin** [comment]
Thank you so much! Let me know if you would like any more info.

**Comment by jaagr** [comment]
This should be fixed with 4a6a36f08f5133587826f6ed212826b7b1eb89a8
Do you mind confirming that it works as expected?

**Comment by jaagr** [comment]
If you want to control how often the values are polled you could set the configuration parameter `poll_interval` in the battery section.

**Comment by ChristopherWMartin** [comment]
Everything seems to be working perfectly now. Thanks for all of your hard work on Lemonbuddy.

**Comment by jaagr** [comment]
You might want to update your package since I found a performance issue with the update. It's fixed in the latest version.

Thanks, and please report any other issues or problems you encounter! Peace.
