### ISSUE TITLE
Supprt for Multiple Batteries

### ISSUE THREAD

**Issue by jediofthecode** [jaagr/lemonbuddy#71]
It seems right now there is no support for systems with more than 1 battery. I am using a lenovo thinkpad t460s which runs 2 seperate batteries internally and have now way of accuratly getting the battery info. Can support please be added for this ?

**Comment by jaagr** [comment]
Hi,

I'm currently working on releasing v2.0 so I won't add any new features until then. I will have a look at it once I'm done. For now you could use a script module and manually calculate the battery info.

**Comment by jaagr** [comment]
On a second thought this could already be done by adding two different battery modules targeting the different batteries.
