### ISSUE TITLE
Locale option broken by 2.0 update

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#74]
Since the 2.0 update (2.0.0.rbeta.5.ge42eb87-1 via lemonbuddy-git on AUR), the locale option seems to be broken because the `date` module is still in english.

Tried `locale = fr_FR.UTF-8` which worked before the update.
I can send you my full config file if needed.

Awesome soft btw.

**Comment by jaagr** [comment]
Thanks for reporting it.. Should be fixed now

**Comment by jaagr** [comment]
dis-moi si tu trouves d'autres choses qui ne marches plus stp... :)
