### ISSUE TITLE
missing libraries for apt-get

### ISSUE THREAD

**Issue by pciavald** [jaagr/lemonbuddy#78]
Hi, 
i'm trying to install lemonbuddy on ubuntu mate 16.04. First I had to install `libxcb-icccm4-dev libxcb-ewmh-dev libxcb-util-dev` on top of what you mentionned in the apt-get command.
Now cmake still fails with this error : 
```
-- ---------------------------
--  Build type: Release
--  Compiler C: /usr/bin/cc
--  Compiler C++: /usr/bin/c++
--  Compiler flags:  -std=c++14 -Wall -Wno-unused-parameter -Wno-unused-local-typedefs
--  + release flags:: -O3 -DNDEBUG -O2
-- ---------------------------
--  Build testsuite        OFF
--  Enable ccache support  OFF
--  Enable alsa support    ON
--  Enable i3 support      ON
--  Enable mpd support     ON
--  Enable network support ON
-- ---------------------------
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xft_LIB (ADVANCED)
    linked by target "xpp" in directory /home/pciavald/Downloads/lemonbuddy/lib/xpp
    linked by target "i3ipc++" in directory /home/pciavald/Downloads/lemonbuddy/lib/i3ipcpp
    linked by target "lemonlib_static" in directory /home/pciavald/Downloads/lemonbuddy/src
    linked by target "lemonbuddy" in directory /home/pciavald/Downloads/lemonbuddy/src

-- Configuring incomplete, errors occurred!
```
thank you for your work, i came here from reddit

**Comment by pciavald** [comment]
i've added `libghc-x11-xft-dev` to the list of packages to install, with its 479 MB of dependencies, now it compiles.

**Comment by jaagr** [comment]
Hi, thanks for reporting the issue.

The README haven't been updated since the update, but I don't think you need the package you mention. The ci runner uses ubuntu 14.04 and it compiles fine using the following packages:

`cmake cmake-data libcppunit-dev libboost-dev libfreetype6-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-ewmh-dev libxcb-icccm4-dev xcb-proto python-xcbgen i3-wm libiw-dev libasound2-dev libmpdclient-dev`

I will update the README accordingly.

**Comment by bartszu** [comment]
Do I have to use I3 as my window manager to use Polybar ?
I am also using Mate with Marco window manager.
During installing dependencies to make it install, it asked for I3.
So I kinda backed off as I am not prepared to us I3.

**Comment by jaagr** [comment]
@bartszu no you don't, but then you have to build it without i3 support, i.e: `cmake -DENABLE_I3=OFF ..`
