### ISSUE TITLE
New offset-x behaviour

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/lemonbuddy#79]
Until version 2.0 'offset_x = N' moved the panel N pixels from the left border of the screen. This allowed me to have 3 panels on top that looked like that: `|_***_***********_***_ |`,

Since version 2.0 new 'offset-x = N' moves the panel from the both sides of the screen at the same time, making my setup impossible to implement with the lemonbuddy. 

My previols config of offset 20; panel 500; offset  540; panel 1480; offset 2040; panel 500 results in unusable middle panel and  an ''error: Failed to setup bar renderer: Resulting bar width is out of bounds' error for the right one.

Can you revert the change to the 'offset-x' behaviour or define offsets from the left and right separately?

**Comment by jaagr** [comment]
Hi and thanks for reporting the issue.

This wasn't intended and I will revert to the old offset behaviour.
