### ISSUE TITLE
Always on top behaviour in 2.0

### ISSUE THREAD

**Issue by AtzeDeVries** [jaagr/lemonbuddy#80]
In bspwm with lemonbuddy < 2.0 when i went to fullscreen mode, the window (node) was ontop of the lemonbar. Now in 2.0 the bar in ontop of the window and interfering with the controls of the window. 

[edit]
the behaviour is a not fully as i explaned.

This behaviour is only if you start lemmonbuddy with `-r` and after it has been automatically reloaded  because of a config change

**Comment by jaagr** [comment]
Hi and thanks for reporting.

Are you using the new configuration option `wm-restack = bspwm`?

**Comment by AtzeDeVries** [comment]
No, i did not. I'll try it and report back. Should this option be places at
the beginning section of the config file?

Op vr 14 okt. 2016 om 10:44 schreef Michael Carlberg <
notifications@github.com>:

**Comment by jaagr** [comment]
Yeah exactly.. it's defined under the `[bar/mybar]` section.

The option removes the need of any custom restacking. Currently supports bspwm and i3.

Please close the issue if it fixes your problem.

**Comment by AtzeDeVries** [comment]
Thnx! That fixed the issue.

**Comment by jaagr** [comment]
Great. For future reference... the reason it doesn't work without the option is that the bar window gets recreated each time the app reloads (so any custom restacking only applies to the first window creation)
