### ISSUE TITLE
segfault with unknown net interface

### ISSUE THREAD

**Issue by pciavald** [jaagr/lemonbuddy#81]
I am sometimes using an external USB wifi card. When i create a module for this interface it works seamlessly, but if the card is not plugged the bar segfaults saying that the interface doesn't exist. It would be great if the error was silently ignored, and it would be amazing if there was a setting for unexisting interface, so that i could display a disconnected icon when it's not connected.

**Comment by jaagr** [comment]
Thanks for reporting... some old code made the application exit if the interface didn't exists.. should be fixed with 6f28605
