### ISSUE TITLE
i3 module freeze when reloading i3

### ISSUE THREAD

**Issue by pciavald** [jaagr/lemonbuddy#83]
launching lemonbuddy from console : 
`lemonbuddy bottom -c ~/dotfiles/i3/lemonbuddyrc`
refreshing i3 (ie mod+maj+R)
lemonbuddy loops on error 
`error: module/i3: Error while handling ipc event (Unexpected EOF while reading header)`
and the i3 module doesn't change the viewed space in the bar anymore (ie i'm on space 4 and it still shows space 3 active)

**Comment by jaagr** [comment]
Thanks for reporting the issue.. I will look into it.

**Comment by pciavald** [comment]
tell me if any log or info can help you  :)

**Comment by jaagr** [comment]
Could you please verify that the referenced commit solves the issue? It works fine for me. If not, re-open the issue.

**Comment by pciavald** [comment]
thank you for the fast handling of bugs :) 
the error looks different now. there's no infinite loop on it but it's still there.
```
error: module/i3: Error while handling ipc event, stopping module...
error: module/i3: Unexpected EOF while reading header
```

**Comment by jaagr** [comment]
The error is actually valid so it should be there, but you can choose to ignore it or you could make sure that lemonbuddy is shut down before restarting. Hm not sure why you couldn't re-open the issue though :-/

**Comment by pciavald** [comment]
i think i would have to be collaborator on your repo to be able to reopen an issue that you (owner) closed. I had mistyped "exec_always" so i skipped the killall script part, now it works perfectly.
