### ISSUE TITLE
New option '-r' not fully working yet

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#85]
When you run two bars with the same config file with the `-r` option, and when you update your config file, sometimes both are reloaded, sometimes only one, sometimes none of them.

**Comment by jaagr** [comment]
Thanks for reporting. I think this is caused by two conflicting inotify watches, but I will look into it. I'd recommend only using the `--reload` flag when setting up the bar.

**Comment by jaagr** [comment]
Closing as the `-r` flag is marked a experimental.
