### ISSUE TITLE
Random error messages

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#88]
Sometimes, I randomly got these messages:

> warning: Action block not closed
> warning: action.command = backlight_percentage p5
> warning: Action block not closed
> warning: action.command = backlight_percentage m5

and/or

> error: module/battery: Failed to read ' 	'

and/or

> error: module/battery: Failed to read '0'

and/or

> terminate called after throwing an instance of 'std::invalid_argument'
> what():  stoull

My config file: https://github.com/Quent42340/dotfiles/blob/master/link/.config/lemonbuddy/config

**Comment by jaagr** [comment]
Thanks for reporting.

At a first glance I see that some of the parameter names needs to be changed to apply to the 2.0 changes.

**Comment by Quent42340** [comment]
Oh yeah sorry I didn't pushed my last modifications, now it's done.

**Comment by Quent42340** [comment]
Don't know if I should have created a new issue for this but, on my top bar (the one with the tray), I got this error message while killing `synapse` and relaunching it, and the bar was gone:

> terminate called after throwing an instance of 'xpp::x::error::window'
> what():  XCB_WINDOW (3)

I don't understand why this happened with `synapse` because it's not using a tray icon (I disabled it).

**Comment by jaagr** [comment]
Are you able to reproduce the error?

**Comment by Quent42340** [comment]
Yes, after killing synapse and relaunching it. I'll try to give you the exact steps later if you're not able to reproduce it.

**Comment by anxsec** [comment]
open teriminator also:
```
terminate called after throwing an instance of 'xpp::x::error::window'
  what():  XCB_WINDOW (3)
```

**Comment by jaagr** [comment]
Is this issue still valid with the latest version?

**Comment by Quent42340** [comment]
Yes, just tried with the same steps than before: "pkill synapse; synapse"

**Comment by jaagr** [comment]
The fixes are made after the last release. I will create a patch release.

**Comment by jaagr** [comment]
OK just pushed the patch release (2.1.5) so please update and try again.

**Comment by Quent42340** [comment]
Ok, perfect, seems fixed. :)
