### ISSUE TITLE
Mouse wheel not working with volume since 2.0

### ISSUE THREAD

**Issue by Quent42340** [jaagr/lemonbuddy#89]
Using mouse wheel to change volume is broken since 2.0. Maybe this is intended?

If possible, add a possibility to choose the incrementation/decrementation step, and make it possible for backlight too, that would be awesome. :)

**Comment by jaagr** [comment]
For me the mouse wheel works fine.

**Comment by Quent42340** [comment]
For me it works fine but only on mpd module, it just doesn't work with volume anymore. :/

I just updated to the last version just in case, and it still doesn't work.

**Comment by jaagr** [comment]
I think this is caused by the configuration. Could you launch the bar with `--stdout` and a line from the output?

**Comment by Quent42340** [comment]
Sure, I got "%{A1:volmute: A4:volup: A5:voldown:}15%%{A A A}" for the volume module.

My full output:
```
%{l}  %{A1:i3-wsfocus-2: U#fba922 +u B#3f3f3f F#fff}    %{A A1:i3-wsfocus-3: -u B- F-}  3  %{A A1:i3-wsfocus-9:}    %{A A1:i3-wsfocus-10:}    %{A A1:i3-wsfocus-11:}    %{A A1:i3-wsfocus-12:}    %{A A1:i3-wsfocus-13:}    %{A A1:i3-wsfocus-18:}    %{A A1:i3-wsfocus-19:}    %{A U-}   %{c}      %{F#999}ven. 14 oct.  %{F#fff}15:17:08%{F-}   %{r}      13G         47G      %{A1:volmute: A4:volup: A5:voldown:}    15%%{A A A}          %{A4:backlight_percentage p5: A5:backlight_percentage m5: +u +o F#bbFFFFFF T3}─────────%{-u -o F#ffFFFFFF}|%{+u +o -u -o A A F- T-}      %{F#66FFFFFF}   not connected%{F-}         %{T3}192.168.1.27%{T-}          100%      %{A1:bash ~/.i3/i3blocks/tetrane login: A3:bash ~/.i3/i3blocks/tetrane logout:}%{A A}     
```

**Comment by jaagr** [comment]
Is this still an issue?

**Comment by reyqn** [comment]
I have exactly the same issue.
I can't tell if this is fixed yet because I'm at work, but I don't remember seeing it working yesterday.
Do you use pulseaudio?

**Comment by jaagr** [comment]
@reyqn Could you show me your config of the volume module

**Comment by reyqn** [comment]
`[module/volume]
type = internal/volume
;master-mixer = Master
format-volume = <ramp-volume> <label-volume>
label-muted = 
label-muted-foreground = #666666

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = `

**Comment by jaagr** [comment]
What's the output of `amixer scontrols`?

**Comment by jaagr** [comment]
Also, I did commit a patch the other day (for issue #96) that fixed issues related to just having the master mixer setup. Have you updated since then?

**Comment by reyqn** [comment]
Well I don't have access to my computer right now. I'm using [this AUR package](https://aur.archlinux.org/packages/lemonbuddy-git/) if I remember well.
I think `amixer scontrols` only returns "Master", so maybe I just didn't get the patch with my AUR package manager. I'll tell you more this evening (in like 6 hours).

**Comment by hthuong09** [comment]
For me, I just installed the latest git version at `3a5ee90`, the module did work. I can mute, increase, decrease volume level by mouse though text on the bar didn't update. But it update when I enter `amixer sset Master 10%-` manual in terminal.

My config

```
[module/volume]
type = internal/volume

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%
label-volume-foreground = ${BAR.foreground}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-foreground = #666

label-muted = %{F#666}%{F#ccfafafa} %percentage%
label-muted-foreground = #99 
```
`amixer scontrols`'s output
```
~ » amixer scontrols
Simple mixer control 'Master',0
Simple mixer control 'Capture',0

```

**Comment by jaagr** [comment]
@reyqn OK, hopefully it will work for you after updating.

@hthuong09 Yeah that's what I was trying to fix yesterday. It works fine for me now. What compiler are you using?

**Comment by hthuong09** [comment]
I am using aur git package. So it should be clang.

**Comment by jaagr** [comment]
Could you try building with `-O1` and see if fixes it.

**Comment by hthuong09** [comment]
```
build/lemonbuddy - [master●] » cmake -O1
-- No build type specified; using Release
-- Boost version: 1.61.0
-- XCB[XCB]: Found component XCB
-- XCB[ICCCM]: Found component ICCCM
-- XCB[EWMH]: Found component EWMH
-- XCB[UTIL]: Found component UTIL
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so
-- Searching for xcbgen with python2
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.5/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-randr.so
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xproto.xml
-- lemonlib_static
-- ---------------------------
--  Build type: Release
--  Compiler C: /usr/bin/cc
--  Compiler C++: /usr/bin/c++
--  Compiler flags:  -std=c++14 -Wall -Wno-unused-parameter -Wno-unused-local-typedefs
--  + release flags:: -O3 -DNDEBUG -O3
-- ---------------------------
--  Build testsuite        OFF
--  Enable ccache support  OFF
--  Enable alsa support    ON
--  Enable i3 support      OFF
--  Enable mpd support     ON
--  Enable network support ON
-- ---------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hthuong/code/build/lemonbuddy
build/lemonbuddy - [master●] » sudo make install
[ 20%] Built target xpp
[ 60%] Built target lemonlib_static
[100%] Built target lemonbuddy
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/man/man1/lemonbuddy.1
-- Up-to-date: /usr/local/share/man/man5/lemonbuddy_config.5
-- Up-to-date: /usr/local/bin/lemonbuddy
-- Up-to-date: /usr/local/share/examples/lemonbuddy/config
-- Up-to-date: /usr/local/share/examples/lemonbuddy/config.bspwm
build/lemonbuddy - [master●] »
```
Did I do it right? And unfortunately, the volume module is still not working correctly.

**Comment by jaagr** [comment]
No it's still using `-O3`.. Run it like this:

`cmake -DCMAKE_CXX_FLAGS=-O1 ..`

**Comment by jaagr** [comment]
It's also not using clang.. `cmake -DCMAKE_CXX_COMPILER=clang++ ..`

**Comment by hthuong09** [comment]
This time with clang++. It gave me [tons of errors](https://gist.github.com/hthuong09/a76334732e6ba61eebba9e605f05fb5a).

**Comment by jaagr** [comment]
It crashed.. looks like the `-O` flag is defined two times.. change the CMakeCache.txt in the build folder to get rid of -O3

**Comment by hthuong09** [comment]
There is only one `O3` in CMakeCache.txt file.
```
//Flags used by the compiler during release builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
```
Remove it still doesn't change release flag

**Comment by jaagr** [comment]
It can still be release but not `-O3`

**Comment by jaagr** [comment]
If you can't remove it, just try running the debug build.. `cmake -DCMAKE_BUILD_TYPE=Debug ..` it has no optimizations on

**Comment by hthuong09** [comment]
Still getting [errors](https://gist.github.com/hthuong09/a76334732e6ba61eebba9e605f05fb5a)

**Comment by jaagr** [comment]
Remove the build foder and create it again to get a clean state..

**Comment by hthuong09** [comment]
I did, still getting the same error.

**Comment by jaagr** [comment]
odd.. i don't know what's wrong with it..

**Comment by Quent42340** [comment]
With the `2.0.0.rbeta.0.g4d24097` the click was working for mute, but the mouse wheel muted too... Since the `2.0.1.r5.g56b4657` update, click and wheel do nothing...

**Comment by jaagr** [comment]
OK, I'll lower optimizations and see if that's the problem.

**Comment by reyqn** [comment]
That's very strange. I have now the same issue as @hthuong09 
Everything works but no visual update. However, if I launch a second instance of lemonbuddy without killing the first one, well the new one still won't visually update, but I can see the first one behind it changing as I mute or change the volume.

**Comment by jaagr** [comment]
Yeah that's probably because it receives the events from the alsa api.. I'm trying to find the thing that is messing up the builds...
