### ISSUE TITLE
add a config for battery interface location

### ISSUE THREAD

**Issue by pciavald** [jaagr/lemonbuddy#91]
```
error: module/battery: battery_module: The file '/sys/class/power_supply/BAT0/capacity' does not exist
```
mine is here : /sys/class/power_supply/BAT1/capacity

**Comment by patrick96** [comment]
You should be able to specify the battery in the battery module like this:
```dosini
battery = BAT1
```

**Comment by jaagr** [comment]
Yeah, this is still done using the option @patrick96 mentioned.

**Comment by pciavald** [comment]
amazing. thanks
