### ISSUE TITLE
module/script: format-* does nothing

### ISSUE THREAD

**Issue by abstrakct** [jaagr/lemonbuddy#97]
Hi. I'm new to lemonbuddy, so forgive me this is my own fault, but this issue seems like a bug to me.
I'm trying to run a simple script to output free space for a filesystem. That works fine. But I can't make any of the format-* settings for the module do anything. E.g. "format-foreground = #00ff00" to set foreground color. I've tried setting "format-padding" to 100 with no effect at all, the same with various settings for format-foreground and -background. 

According to the wiki, it should work:
```
  ; Available tags:
  ;   <output> (default)
  ;format = <output>
  format-background = #999
  format-foreground = #000
  format-padding = 4
```

And from what I can tell from the source code (it's a bit too modern c++ for me), it should work. But it doesn't. Unless I'm doing something wrong.

I also tried making the script itself output formatting codes ( like %{F#00ff00} ), but that didn't work. The same goes for adding formatting codes to the "format = <output>" line.

It would be very nice to be able to set the display color of the output from a script.

**Comment by jaagr** [comment]
Hi and thanks for reporting. This should work, at least it did before. I will have a look at it.

**Comment by jaagr** [comment]
Found the bug. Could you please verify that it works.

**Comment by abstrakct** [comment]
Yes, it works now! -foreground, -background, and -padding.

**Comment by jaagr** [comment]
Great
