### ISSUE TITLE
module/cpu: core 0 is ignored

### ISSUE THREAD

**Issue by abstrakct** [jaagr/lemonbuddy#98]
I noticed core 0 on my system (AMD quadcore cpu) was ignored by the cpu module.
The problem seems to be in cpu.hpp in include/modules, lines 135 & 136:

```
else if (!core)
  return 0;
```

Since "if (!core)" basically means "if (core == 0)" this obviously makes the code ignore core 0.
Commenting out those lines makes the cpu module take all 4 cores into account.

**Comment by jaagr** [comment]
That's a sneaky one. No idea why I changed it to `else if (!core)` because before 2.0 it was `else if (core < 0)`
I'll patch it.
