### ISSUE TITLE
Clickable areas in custom/script

### ISSUE THREAD

**Issue by birjolaxew** [jaagr/lemonbuddy#99]
Would it be possible to create a way for external scripts to provide multiple clickable areas in the shown text? Using lemonbar-like tokens would probably be the easiest.

My specific use case is a wifi menu; a clickable `internal/network` which shows available networks when clicked, and connects when one is clicked, similar to a `custom/menu`. This would require clickable areas to simulate a menu, which isn't possible using only left/middle/right clicking.

**Comment by jaagr** [comment]
You can already use lemonbar tokens. All %{...} tags used in lemonbar is implemented.

**Comment by birjolaxew** [comment]
Ah, neat. Is that mentioned on the wiki?

If I were to use a menu, how would I make it so that the menu items (and `label-open`) are given by the output of an external script? Based on the wiki, I don't see a way to do that.

**Comment by jaagr** [comment]
Oh I must have misunderstood you. That's not possible with the current module..

**Comment by birjolaxew** [comment]
Thanks for the help anyway - support of lemonbar tokens lets me code it myself :)

**Comment by Tmplt** [comment]
Reopening this: is this still possible in 2.0 and above now that the bar is internal?

**Comment by NBonaparte** [comment]
Yes.
